In [1]:
import pandas as pd
from datetime import time

In [2]:
prices = pd.read_csv("Price_2017_CPS.csv")

In [3]:
prices

,OPERATION_DATE,HOUR_ENDING,INTERVAL_ENDING,TOUTYPE,MARKET,ZONE,PRICE
0,1/1/2017,100,15,OFF-PEAK,Real Time,Load Zone CPS,24.10
1,1/1/2017,100,30,OFF-PEAK,Real Time,Load Zone CPS,23.76
2,1/1/2017,100,45,OFF-PEAK,Real Time,Load Zone CPS,22.87
3,1/1/2017,100,100,OFF-PEAK,Real Time,Load Zone CPS,22.70
4,1/1/2017,200,115,OFF-PEAK,Real Time,Load Zone CPS,22.07
5,1/1/2017,200,130,OFF-PEAK,Real Time,Load Zone CPS,21.87
6,1/1/2017,200,145,OFF-PEAK,Real Time,Load Zone CPS,20.92
7,1/1/2017,200,200,OFF-PEAK,Real Time,Load Zone CPS,21.00
8,1/1/2017,300,215,OFF-PEAK,Real Time,Load Zone CPS,21.11
9,1/1/2017,300,230,OFF-PEAK,Real Time,Load Zone CPS,20.94
10,1/1/2017,300,245,OFF-PEAK,Real Time,Load Zone CPS,20.60
11,1/1/2017,300,300,OFF-PEAK,Real Time,Load Zone CPS,20.29
12,1/1/2017,400,315,OFF-PEAK,Real Time,Load Zone CPS,20.23
13,1/1/2017,400,330,OFF-PEAK,Real Time,Load Zone CPS,20.32
14,1/1/2017,400,345,OFF-PEAK,Real Time,Load Zone CPS,20.26
15,1/1/2017,400,400,OFF-PEAK,Real Time,Load Zone CPS,20.27
16,1/1/2017,500,415,OFF-PEAK,Real Time,Load Zone CPS,20.43
17,1/1/2017,500,430,OFF-PEAK,Real Time,Load Zone CPS,20.21
18,1/1/2017,500,445,OFF-PEAK,Real Time,Load Zone CPS,20.04
19,1/1/2017,500,500,OFF-PEAK,Real Time,Load Zone CPS,19.80
20,1/1/2017,600,515,OFF-PEAK,Real Time,Load Zone CPS,19.80
21,1/1/2017,600,530,OFF-PEAK,Real Time,Load Zone CPS,19.80
22,1/1/2017,600,545,OFF-PEAK,Real Time,Load Zone CPS,19.80
23,1/1/2017,600,600,OFF-PEAK,Real Time,Load Zone CPS,19.77
24,1/1/2017,700,615,PEAKWE,Real Time,Load Zone CPS,19.71
25,1/1/2017,700,630,PEAKWE,Real Time,Load Zone CPS,19.71
26,1/1/2017,700,645,PEAKWE,Real Time,Load Zone CPS,19.72
27,1/1/2017,700,700,PEAKWE,Real Time,Load Zone CPS,19.75
28,1/1/2017,800,715,PEAKWE,Real Time,Load Zone CPS,19.80
29,1/1/2017,800,730,PEAKWE,Real Time,Load Zone CPS,19.78
...,...,...,...,...,...,...,...
35010,12/31/2017,1700,1645,PEAKWE,Real Time,Load Zone CPS,22.73
35011,12/31/2017,1700,1700,PEAKWE,Real Time,Load Zone CPS,23.07
35012,12/31/2017,1800,1715,PEAKWE,Real Time,Load Zone CPS,24.65
35013,12/31/2017,1800,1730,PEAKWE,Real Time,Load Zone CPS,28.03
35014,12/31/2017,1800,1745,PEAKWE,Real Time,Load Zone CPS,30.35
35015,12/31/2017,1800,1800,PEAKWE,Real Time,Load Zone CPS,31.43
35016,12/31/2017,1900,1815,PEAKWE,Real Time,Load Zone CPS,30.78
35017,12/31/2017,1900,1830,PEAKWE,Real Time,Load Zone CPS,30.77
35018,12/31/2017,1900,1845,PEAKWE,Real Time,Load Zone CPS,30.56
35019,12/31/2017,1900,1900,PEAKWE,Real Time,Load Zone CPS,29.47
35020,12/31/2017,2000,1915,PEAKWE,Real Time,Load Zone CPS,29.42
35021,12/31/2017,2000,1930,PEAKWE,Real Time,Load Zone CPS,28.96
35022,12/31/2017,2000,1945,PEAKWE,Real Time,Load Zone CPS,28.04
35023,12/31/2017,2000,2000,PEAKWE,Real Time,Load Zone CPS,27.09
35024,12/31/2017,2100,2015,PEAKWE,Real Time,Load Zone CPS,28.26
35025,12/31/2017,2100,2030,PEAKWE,Real Time,Load Zone CPS,28.33
35026,12/31/2017,2100,2045,PEAKWE,Real Time,Load Zone CPS,28.70
35027,12/31/2017,2100,2100,PEAKWE,Real Time,Load Zone CPS,28.11
35028,12/31/2017,2200,2115,PEAKWE,Real Time,Load Zone CPS,26.63
35029,12/31/2017,2200,2130,PEAKWE,Real Time,Load Zone CPS,25.59
35030,12/31/2017,2200,2145,PEAKWE,Real Time,Load Zone CPS,25.15
35031,12/31/2017,2200,2200,PEAKWE,Real Time,Load Zone CPS,25.68
35032,12/31/2017,2300,2215,OFF-PEAK,Real Time,Load Zone CPS,24.47
35033,12/31/2017,2300,2230,OFF-PEAK,Real Time,Load Zone CPS,24.11
35034,12/31/2017,2300,2245,OFF-PEAK,Real Time,Load Zone CPS,24.07
35035,12/31/2017,2300,2300,OFF-PEAK,Real Time,Load Zone CPS,23.66
35036,12/31/2017,2400,2315,OFF-PEAK,Real Time,Load Zone CPS,22.95
35037,12/31/2017,2400,2330,OFF-PEAK,Real Time,Load Zone CPS,22.81
35038,12/31/2017,2400,2345,OFF-PEAK,Real Time,Load Zone CPS,22.84
35039,12/31/2017,2400,2400,OFF-PEAK,Real Time,Load Zone CPS,22.68

In [4]:
prices['hour'] = pd.to_numeric(prices.HOUR_ENDING, errors=('coerce'))//100 - 1
prices['minute'] = (pd.to_numeric(prices.INTERVAL_ENDING, errors='coerce') - pd.to_numeric(prices.HOUR_ENDING, errors='coerce') + 100)%100
prices = prices.dropna()
prices

,OPERATION_DATE,HOUR_ENDING,INTERVAL_ENDING,TOUTYPE,MARKET,ZONE,PRICE,hour,minute
0,1/1/2017,100,15,OFF-PEAK,Real Time,Load Zone CPS,24.10,0.0,15.0
1,1/1/2017,100,30,OFF-PEAK,Real Time,Load Zone CPS,23.76,0.0,30.0
2,1/1/2017,100,45,OFF-PEAK,Real Time,Load Zone CPS,22.87,0.0,45.0
3,1/1/2017,100,100,OFF-PEAK,Real Time,Load Zone CPS,22.70,0.0,0.0
4,1/1/2017,200,115,OFF-PEAK,Real Time,Load Zone CPS,22.07,1.0,15.0
5,1/1/2017,200,130,OFF-PEAK,Real Time,Load Zone CPS,21.87,1.0,30.0
6,1/1/2017,200,145,OFF-PEAK,Real Time,Load Zone CPS,20.92,1.0,45.0
7,1/1/2017,200,200,OFF-PEAK,Real Time,Load Zone CPS,21.00,1.0,0.0
8,1/1/2017,300,215,OFF-PEAK,Real Time,Load Zone CPS,21.11,2.0,15.0
9,1/1/2017,300,230,OFF-PEAK,Real Time,Load Zone CPS,20.94,2.0,30.0
10,1/1/2017,300,245,OFF-PEAK,Real Time,Load Zone CPS,20.60,2.0,45.0
11,1/1/2017,300,300,OFF-PEAK,Real Time,Load Zone CPS,20.29,2.0,0.0
12,1/1/2017,400,315,OFF-PEAK,Real Time,Load Zone CPS,20.23,3.0,15.0
13,1/1/2017,400,330,OFF-PEAK,Real Time,Load Zone CPS,20.32,3.0,30.0
14,1/1/2017,400,345,OFF-PEAK,Real Time,Load Zone CPS,20.26,3.0,45.0
15,1/1/2017,400,400,OFF-PEAK,Real Time,Load Zone CPS,20.27,3.0,0.0
16,1/1/2017,500,415,OFF-PEAK,Real Time,Load Zone CPS,20.43,4.0,15.0
17,1/1/2017,500,430,OFF-PEAK,Real Time,Load Zone CPS,20.21,4.0,30.0
18,1/1/2017,500,445,OFF-PEAK,Real Time,Load Zone CPS,20.04,4.0,45.0
19,1/1/2017,500,500,OFF-PEAK,Real Time,Load Zone CPS,19.80,4.0,0.0
20,1/1/2017,600,515,OFF-PEAK,Real Time,Load Zone CPS,19.80,5.0,15.0
21,1/1/2017,600,530,OFF-PEAK,Real Time,Load Zone CPS,19.80,5.0,30.0
22,1/1/2017,600,545,OFF-PEAK,Real Time,Load Zone CPS,19.80,5.0,45.0
23,1/1/2017,600,600,OFF-PEAK,Real Time,Load Zone CPS,19.77,5.0,0.0
24,1/1/2017,700,615,PEAKWE,Real Time,Load Zone CPS,19.71,6.0,15.0
25,1/1/2017,700,630,PEAKWE,Real Time,Load Zone CPS,19.71,6.0,30.0
26,1/1/2017,700,645,PEAKWE,Real Time,Load Zone CPS,19.72,6.0,45.0
27,1/1/2017,700,700,PEAKWE,Real Time,Load Zone CPS,19.75,6.0,0.0
28,1/1/2017,800,715,PEAKWE,Real Time,Load Zone CPS,19.80,7.0,15.0
29,1/1/2017,800,730,PEAKWE,Real Time,Load Zone CPS,19.78,7.0,30.0
...,...,...,...,...,...,...,...,...,...
35010,12/31/2017,1700,1645,PEAKWE,Real Time,Load Zone CPS,22.73,16.0,45.0
35011,12/31/2017,1700,1700,PEAKWE,Real Time,Load Zone CPS,23.07,16.0,0.0
35012,12/31/2017,1800,1715,PEAKWE,Real Time,Load Zone CPS,24.65,17.0,15.0
35013,12/31/2017,1800,1730,PEAKWE,Real Time,Load Zone CPS,28.03,17.0,30.0
35014,12/31/2017,1800,1745,PEAKWE,Real Time,Load Zone CPS,30.35,17.0,45.0
35015,12/31/2017,1800,1800,PEAKWE,Real Time,Load Zone CPS,31.43,17.0,0.0
35016,12/31/2017,1900,1815,PEAKWE,Real Time,Load Zone CPS,30.78,18.0,15.0
35017,12/31/2017,1900,1830,PEAKWE,Real Time,Load Zone CPS,30.77,18.0,30.0
35018,12/31/2017,1900,1845,PEAKWE,Real Time,Load Zone CPS,30.56,18.0,45.0
35019,12/31/2017,1900,1900,PEAKWE,Real Time,Load Zone CPS,29.47,18.0,0.0
35020,12/31/2017,2000,1915,PEAKWE,Real Time,Load Zone CPS,29.42,19.0,15.0
35021,12/31/2017,2000,1930,PEAKWE,Real Time,Load Zone CPS,28.96,19.0,30.0
35022,12/31/2017,2000,1945,PEAKWE,Real Time,Load Zone CPS,28.04,19.0,45.0
35023,12/31/2017,2000,2000,PEAKWE,Real Time,Load Zone CPS,27.09,19.0,0.0
35024,12/31/2017,2100,2015,PEAKWE,Real Time,Load Zone CPS,28.26,20.0,15.0
35025,12/31/2017,2100,2030,PEAKWE,Real Time,Load Zone CPS,28.33,20.0,30.0
35026,12/31/2017,2100,2045,PEAKWE,Real Time,Load Zone CPS,28.70,20.0,45.0
35027,12/31/2017,2100,2100,PEAKWE,Real Time,Load Zone CPS,28.11,20.0,0.0
35028,12/31/2017,2200,2115,PEAKWE,Real Time,Load Zone CPS,26.63,21.0,15.0
35029,12/31/2017,2200,2130,PEAKWE,Real Time,Load Zone CPS,25.59,21.0,30.0
35030,12/31/2017,2200,2145,PEAKWE,Real Time,Load Zone CPS,25.15,21.0,45.0
35031,12/31/2017,2200,2200,PEAKWE,Real Time,Load Zone CPS,25.68,21.0,0.0
35032,12/31/2017,2300,2215,OFF-PEAK,Real Time,Load Zone CPS,24.47,22.0,15.0
35033,12/31/2017,2300,2230,OFF-PEAK,Real Time,Load Zone CPS,24.11,22.0,30.0
35034,12/31/2017,2300,2245,OFF-PEAK,Real Time,Load Zone CPS,24.07,22.0,45.0
35035,12/31/2017,2300,2300,OFF-PEAK,Real Time,Load Zone CPS,23.66,22.0,0.0
35036,12/31/2017,2400,2315,OFF-PEAK,Real Time,Load Zone CPS,22.95,23.0,15.0
35037,12/31/2017,2400,2330,OFF-PEAK,Real Time,Load Zone CPS,22.81,23.0,30.0
35038,12/31/2017,2400,2345,OFF-PEAK,Real Time,Load Zone CPS,22.84,23.0,45.0
35039,12/31/2017,2400,2400,OFF-PEAK,Real Time,Load Zone CPS,22.68,23.0,0.0

In [5]:
from pytz import UTC

In [6]:
prices['timestamp'] = prices.apply(lambda row: pd.Timestamp('{0} {1}:{2}'.format(row.OPERATION_DATE, row.hour, row.minute)), axis=1)
prices

c:\users\anish\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,OPERATION_DATE,HOUR_ENDING,INTERVAL_ENDING,TOUTYPE,MARKET,ZONE,PRICE,hour,minute,timestamp
0,1/1/2017,100,15,OFF-PEAK,Real Time,Load Zone CPS,24.10,0.0,15.0,2017-01-01 00:15:00
1,1/1/2017,100,30,OFF-PEAK,Real Time,Load Zone CPS,23.76,0.0,30.0,2017-01-01 00:30:00
2,1/1/2017,100,45,OFF-PEAK,Real Time,Load Zone CPS,22.87,0.0,45.0,2017-01-01 00:45:00
3,1/1/2017,100,100,OFF-PEAK,Real Time,Load Zone CPS,22.70,0.0,0.0,2017-01-01 00:00:00
4,1/1/2017,200,115,OFF-PEAK,Real Time,Load Zone CPS,22.07,1.0,15.0,2017-01-01 01:15:00
5,1/1/2017,200,130,OFF-PEAK,Real Time,Load Zone CPS,21.87,1.0,30.0,2017-01-01 01:30:00
6,1/1/2017,200,145,OFF-PEAK,Real Time,Load Zone CPS,20.92,1.0,45.0,2017-01-01 01:45:00
7,1/1/2017,200,200,OFF-PEAK,Real Time,Load Zone CPS,21.00,1.0,0.0,2017-01-01 01:00:00
8,1/1/2017,300,215,OFF-PEAK,Real Time,Load Zone CPS,21.11,2.0,15.0,2017-01-01 02:15:00
9,1/1/2017,300,230,OFF-PEAK,Real Time,Load Zone CPS,20.94,2.0,30.0,2017-01-01 02:30:00
10,1/1/2017,300,245,OFF-PEAK,Real Time,Load Zone CPS,20.60,2.0,45.0,2017-01-01 02:45:00
11,1/1/2017,300,300,OFF-PEAK,Real Time,Load Zone CPS,20.29,2.0,0.0,2017-01-01 02:00:00
12,1/1/2017,400,315,OFF-PEAK,Real Time,Load Zone CPS,20.23,3.0,15.0,2017-01-01 03:15:00
13,1/1/2017,400,330,OFF-PEAK,Real Time,Load Zone CPS,20.32,3.0,30.0,2017-01-01 03:30:00
14,1/1/2017,400,345,OFF-PEAK,Real Time,Load Zone CPS,20.26,3.0,45.0,2017-01-01 03:45:00
15,1/1/2017,400,400,OFF-PEAK,Real Time,Load Zone CPS,20.27,3.0,0.0,2017-01-01 03:00:00
16,1/1/2017,500,415,OFF-PEAK,Real Time,Load Zone CPS,20.43,4.0,15.0,2017-01-01 04:15:00
17,1/1/2017,500,430,OFF-PEAK,Real Time,Load Zone CPS,20.21,4.0,30.0,2017-01-01 04:30:00
18,1/1/2017,500,445,OFF-PEAK,Real Time,Load Zone CPS,20.04,4.0,45.0,2017-01-01 04:45:00
19,1/1/2017,500,500,OFF-PEAK,Real Time,Load Zone CPS,19.80,4.0,0.0,2017-01-01 04:00:00
20,1/1/2017,600,515,OFF-PEAK,Real Time,Load Zone CPS,19.80,5.0,15.0,2017-01-01 05:15:00
21,1/1/2017,600,530,OFF-PEAK,Real Time,Load Zone CPS,19.80,5.0,30.0,2017-01-01 05:30:00
22,1/1/2017,600,545,OFF-PEAK,Real Time,Load Zone CPS,19.80,5.0,45.0,2017-01-01 05:45:00
23,1/1/2017,600,600,OFF-PEAK,Real Time,Load Zone CPS,19.77,5.0,0.0,2017-01-01 05:00:00
24,1/1/2017,700,615,PEAKWE,Real Time,Load Zone CPS,19.71,6.0,15.0,2017-01-01 06:15:00
25,1/1/2017,700,630,PEAKWE,Real Time,Load Zone CPS,19.71,6.0,30.0,2017-01-01 06:30:00
26,1/1/2017,700,645,PEAKWE,Real Time,Load Zone CPS,19.72,6.0,45.0,2017-01-01 06:45:00
27,1/1/2017,700,700,PEAKWE,Real Time,Load Zone CPS,19.75,6.0,0.0,2017-01-01 06:00:00
28,1/1/2017,800,715,PEAKWE,Real Time,Load Zone CPS,19.80,7.0,15.0,2017-01-01 07:15:00
29,1/1/2017,800,730,PEAKWE,Real Time,Load Zone CPS,19.78,7.0,30.0,2017-01-01 07:30:00
...,...,...,...,...,...,...,...,...,...,...
35010,12/31/2017,1700,1645,PEAKWE,Real Time,Load Zone CPS,22.73,16.0,45.0,2017-12-31 16:45:00
35011,12/31/2017,1700,1700,PEAKWE,Real Time,Load Zone CPS,23.07,16.0,0.0,2017-12-31 16:00:00
35012,12/31/2017,1800,1715,PEAKWE,Real Time,Load Zone CPS,24.65,17.0,15.0,2017-12-31 17:15:00
35013,12/31/2017,1800,1730,PEAKWE,Real Time,Load Zone CPS,28.03,17.0,30.0,2017-12-31 17:30:00
35014,12/31/2017,1800,1745,PEAKWE,Real Time,Load Zone CPS,30.35,17.0,45.0,2017-12-31 17:45:00
35015,12/31/2017,1800,1800,PEAKWE,Real Time,Load Zone CPS,31.43,17.0,0.0,2017-12-31 17:00:00
35016,12/31/2017,1900,1815,PEAKWE,Real Time,Load Zone CPS,30.78,18.0,15.0,2017-12-31 18:15:00
35017,12/31/2017,1900,1830,PEAKWE,Real Time,Load Zone CPS,30.77,18.0,30.0,2017-12-31 18:30:00
35018,12/31/2017,1900,1845,PEAKWE,Real Time,Load Zone CPS,30.56,18.0,45.0,2017-12-31 18:45:00
35019,12/31/2017,1900,1900,PEAKWE,Real Time,Load Zone CPS,29.47,18.0,0.0,2017-12-31 18:00:00
35020,12/31/2017,2000,1915,PEAKWE,Real Time,Load Zone CPS,29.42,19.0,15.0,2017-12-31 19:15:00
35021,12/31/2017,2000,1930,PEAKWE,Real Time,Load Zone CPS,28.96,19.0,30.0,2017-12-31 19:30:00
35022,12/31/2017,2000,1945,PEAKWE,Real Time,Load Zone CPS,28.04,19.0,45.0,2017-12-31 19:45:00
35023,12/31/2017,2000,2000,PEAKWE,Real Time,Load Zone CPS,27.09,19.0,0.0,2017-12-31 19:00:00
35024,12/31/2017,2100,2015,PEAKWE,Real Time,Load Zone CPS,28.26,20.0,15.0,2017-12-31 20:15:00
35025,12/31/2017,2100,2030,PEAKWE,Real Time,Load Zone CPS,28.33,20.0,30.0,2017-12-31 20:30:00
35026,12/31/2017,2100,2045,PEAKWE,Real Time,Load Zone CPS,28.70,20.0,45.0,2017-12-31 20:45:00
35027,12/31/2017,2100,2100,PEAKWE,Real Time,Load Zone CPS,28.11,20.0,0.0,2017-12-31 20:00:00
35028,12/31/2017,2200,2115,PEAKWE,Real Time,Load Zone CPS,26.63,21.0,15.0,2017-12-31 21:15:00
35029,12/31/2017,2200,2130,PEAKWE,Real Time,Load Zone CPS,25.59,21.0,30.0,2017-12-31 21:30:00
35030,12/31/2017,2200,2145,PEAKWE,Real Time,Load Zone CPS,25.15,21.0,45.0,2017-12-31 21:45:00
35031,12/31/2017,2200,2200,PEAKWE,Real Time,Load Zone CPS,25.68,21.0,0.0,2017-12-31 21:00:00
35032,12/31/2017,2300,2215,OFF-PEAK,Real Time,Load Zone CPS,24.47,22.0,15.0,2017-12-31 22:15:00
35033,12/31/2017,2300,2230,OFF-PEAK,Real Time,Load Zone CPS,24.11,22.0,30.0,2017-12-31 22:30:00
35034,12/31/2017,2300,2245,OFF-PEAK,Real Time,Load Zone CPS,24.07,22.0,45.0,2017-12-31 22:45:00
35035,12/31/2017,2300,2300,OFF-PEAK,Real Time,Load Zone CPS,23.66,22.0,0.0,2017-12-31 22:00:00
35036,12/31/2017,2400,2315,OFF-PEAK,Real Time,Load Zone CPS,22.95,23.0,15.0,2017-12-31 23:15:00
35037,12/31/2017,2400,2330,OFF-PEAK,Real Time,Load Zone CPS,22.81,23.0,30.0,2017-12-31 23:30:00
35038,12/31/2017,2400,2345,OFF-PEAK,Real Time,Load Zone CPS,22.84,23.0,45.0,2017-12-31 23:45:00
35039,12/31/2017,2400,2400,OFF-PEAK,Real Time,Load Zone CPS,22.68,23.0,0.0,2017-12-31 23:00:00

In [7]:
prices = prices.drop(columns=['OPERATION_DATE', 'HOUR_ENDING', 'INTERVAL_ENDING', 'TOUTYPE', 'MARKET', 'ZONE'])
prices

       PRICE  hour  minute           timestamp
0      24.10   0.0    15.0 2017-01-01 00:15:00
1      23.76   0.0    30.0 2017-01-01 00:30:00
2      22.87   0.0    45.0 2017-01-01 00:45:00
3      22.70   0.0     0.0 2017-01-01 00:00:00
4      22.07   1.0    15.0 2017-01-01 01:15:00
5      21.87   1.0    30.0 2017-01-01 01:30:00
6      20.92   1.0    45.0 2017-01-01 01:45:00
7      21.00   1.0     0.0 2017-01-01 01:00:00
8      21.11   2.0    15.0 2017-01-01 02:15:00
9      20.94   2.0    30.0 2017-01-01 02:30:00
10     20.60   2.0    45.0 2017-01-01 02:45:00
11     20.29   2.0     0.0 2017-01-01 02:00:00
12     20.23   3.0    15.0 2017-01-01 03:15:00
13     20.32   3.0    30.0 2017-01-01 03:30:00
14     20.26   3.0    45.0 2017-01-01 03:45:00
15     20.27   3.0     0.0 2017-01-01 03:00:00
16     20.43   4.0    15.0 2017-01-01 04:15:00
17     20.21   4.0    30.0 2017-01-01 04:30:00
18     20.04   4.0    45.0 2017-01-01 04:45:00
19     19.80   4.0     0.0 2017-01-01 04:00:00
20     19.80   5.0    15.0 2017-01-01 05:15:00
21     19.80   5.0    30.0 2017-01-01 05:30:00
22     19.80   5.0    45.0 2017-01-01 05:45:00
23     19.77   5.0     0.0 2017-01-01 05:00:00
24     19.71   6.0    15.0 2017-01-01 06:15:00
25     19.71   6.0    30.0 2017-01-01 06:30:00
26     19.72   6.0    45.0 2017-01-01 06:45:00
27     19.75   6.0     0.0 2017-01-01 06:00:00
28     19.80   7.0    15.0 2017-01-01 07:15:00
29     19.78   7.0    30.0 2017-01-01 07:30:00
...      ...   ...     ...                 ...
35010  22.73  16.0    45.0 2017-12-31 16:45:00
35011  23.07  16.0     0.0 2017-12-31 16:00:00
35012  24.65  17.0    15.0 2017-12-31 17:15:00
35013  28.03  17.0    30.0 2017-12-31 17:30:00
35014  30.35  17.0    45.0 2017-12-31 17:45:00
35015  31.43  17.0     0.0 2017-12-31 17:00:00
35016  30.78  18.0    15.0 2017-12-31 18:15:00
35017  30.77  18.0    30.0 2017-12-31 18:30:00
35018  30.56  18.0    45.0 2017-12-31 18:45:00
35019  29.47  18.0     0.0 2017-12-31 18:00:00
35020  29.42  19.0    15.0 2017-12-31 19:15:00
35021  28.96  19.0    30.0 2017-12-31 19:30:00
35022  28.04  19.0    45.0 2017-12-31 19:45:00
35023  27.09  19.0     0.0 2017-12-31 19:00:00
35024  28.26  20.0    15.0 2017-12-31 20:15:00
35025  28.33  20.0    30.0 2017-12-31 20:30:00
35026  28.70  20.0    45.0 2017-12-31 20:45:00
35027  28.11  20.0     0.0 2017-12-31 20:00:00
35028  26.63  21.0    15.0 2017-12-31 21:15:00
35029  25.59  21.0    30.0 2017-12-31 21:30:00
35030  25.15  21.0    45.0 2017-12-31 21:45:00
35031  25.68  21.0     0.0 2017-12-31 21:00:00
35032  24.47  22.0    15.0 2017-12-31 22:15:00
35033  24.11  22.0    30.0 2017-12-31 22:30:00
35034  24.07  22.0    45.0 2017-12-31 22:45:00
35035  23.66  22.0     0.0 2017-12-31 22:00:00
35036  22.95  23.0    15.0 2017-12-31 23:15:00
35037  22.81  23.0    30.0 2017-12-31 23:30:00
35038  22.84  23.0    45.0 2017-12-31 23:45:00
35039  22.68  23.0     0.0 2017-12-31 23:00:00

[35036 rows x 4 columns]

In [8]:
prices['price'] = pd.to_numeric(prices['PRICE'])
prices = prices.drop(columns=['PRICE'])
prices

       hour  minute           timestamp  price
0       0.0    15.0 2017-01-01 00:15:00  24.10
1       0.0    30.0 2017-01-01 00:30:00  23.76
2       0.0    45.0 2017-01-01 00:45:00  22.87
3       0.0     0.0 2017-01-01 00:00:00  22.70
4       1.0    15.0 2017-01-01 01:15:00  22.07
5       1.0    30.0 2017-01-01 01:30:00  21.87
6       1.0    45.0 2017-01-01 01:45:00  20.92
7       1.0     0.0 2017-01-01 01:00:00  21.00
8       2.0    15.0 2017-01-01 02:15:00  21.11
9       2.0    30.0 2017-01-01 02:30:00  20.94
10      2.0    45.0 2017-01-01 02:45:00  20.60
11      2.0     0.0 2017-01-01 02:00:00  20.29
12      3.0    15.0 2017-01-01 03:15:00  20.23
13      3.0    30.0 2017-01-01 03:30:00  20.32
14      3.0    45.0 2017-01-01 03:45:00  20.26
15      3.0     0.0 2017-01-01 03:00:00  20.27
16      4.0    15.0 2017-01-01 04:15:00  20.43
17      4.0    30.0 2017-01-01 04:30:00  20.21
18      4.0    45.0 2017-01-01 04:45:00  20.04
19      4.0     0.0 2017-01-01 04:00:00  19.80
20      5.0    15.0 2017-01-01 05:15:00  19.80
21      5.0    30.0 2017-01-01 05:30:00  19.80
22      5.0    45.0 2017-01-01 05:45:00  19.80
23      5.0     0.0 2017-01-01 05:00:00  19.77
24      6.0    15.0 2017-01-01 06:15:00  19.71
25      6.0    30.0 2017-01-01 06:30:00  19.71
26      6.0    45.0 2017-01-01 06:45:00  19.72
27      6.0     0.0 2017-01-01 06:00:00  19.75
28      7.0    15.0 2017-01-01 07:15:00  19.80
29      7.0    30.0 2017-01-01 07:30:00  19.78
...     ...     ...                 ...    ...
35010  16.0    45.0 2017-12-31 16:45:00  22.73
35011  16.0     0.0 2017-12-31 16:00:00  23.07
35012  17.0    15.0 2017-12-31 17:15:00  24.65
35013  17.0    30.0 2017-12-31 17:30:00  28.03
35014  17.0    45.0 2017-12-31 17:45:00  30.35
35015  17.0     0.0 2017-12-31 17:00:00  31.43
35016  18.0    15.0 2017-12-31 18:15:00  30.78
35017  18.0    30.0 2017-12-31 18:30:00  30.77
35018  18.0    45.0 2017-12-31 18:45:00  30.56
35019  18.0     0.0 2017-12-31 18:00:00  29.47
35020  19.0    15.0 2017-12-31 19:15:00  29.42
35021  19.0    30.0 2017-12-31 19:30:00  28.96
35022  19.0    45.0 2017-12-31 19:45:00  28.04
35023  19.0     0.0 2017-12-31 19:00:00  27.09
35024  20.0    15.0 2017-12-31 20:15:00  28.26
35025  20.0    30.0 2017-12-31 20:30:00  28.33
35026  20.0    45.0 2017-12-31 20:45:00  28.70
35027  20.0     0.0 2017-12-31 20:00:00  28.11
35028  21.0    15.0 2017-12-31 21:15:00  26.63
35029  21.0    30.0 2017-12-31 21:30:00  25.59
35030  21.0    45.0 2017-12-31 21:45:00  25.15
35031  21.0     0.0 2017-12-31 21:00:00  25.68
35032  22.0    15.0 2017-12-31 22:15:00  24.47
35033  22.0    30.0 2017-12-31 22:30:00  24.11
35034  22.0    45.0 2017-12-31 22:45:00  24.07
35035  22.0     0.0 2017-12-31 22:00:00  23.66
35036  23.0    15.0 2017-12-31 23:15:00  22.95
35037  23.0    30.0 2017-12-31 23:30:00  22.81
35038  23.0    45.0 2017-12-31 23:45:00  22.84
35039  23.0     0.0 2017-12-31 23:00:00  22.68

[35036 rows x 4 columns]

In [9]:
feb17 = pd.read_csv("feb_2017.csv")
feb17

          a.local_interval_time  a.lp_value      b.lat     b.long  b.u_id
0         2017-02-18 00:00:00.0      0.1794  29.658424 -98.498985    4236
1         2017-02-18 00:00:00.0      0.3000  29.596559 -98.633834    8357
2         2017-02-18 00:00:00.0      0.2046  29.505626 -98.614334    6458
3         2017-02-18 00:00:00.0      0.1290  29.434826 -98.560292    2733
4         2017-02-18 00:00:00.0      0.0768  29.605972 -98.465610    2335
5         2017-02-18 00:00:00.0      0.0222  29.601221 -98.629271    2541
6         2017-02-18 00:00:00.0      0.8682  29.427144 -98.645880    4281
7         2017-02-18 00:00:00.0      0.1872  29.438924 -98.443323    5734
8         2017-02-18 00:00:00.0      0.0834  29.390688 -98.518955    5218
9         2017-02-18 00:00:00.0      0.0858  29.439137 -98.425751    4000
10        2017-02-18 00:00:00.0      0.0018  29.411853 -98.638683    1795
11        2017-02-18 00:00:00.0      0.5922  29.522997 -98.549039    1532
12        2017-02-18 00:00:00.0      0.1866  29.554641 -98.540696    1383
13        2017-02-18 00:00:00.0      0.0480  29.491357 -98.431435    7906
14        2017-02-18 00:00:00.0      0.1512  29.655001 -98.455353    4105
15        2017-02-18 00:00:00.0      0.1416  29.680129 -98.465453    8207
16        2017-02-18 00:00:00.0      0.0234  29.451137 -98.487824     267
17        2017-02-18 00:00:00.0      0.0306  29.508763 -98.486142    6059
18        2017-02-18 00:00:00.0      0.5436  29.354902 -98.421906    2052
19        2017-02-18 00:00:00.0      0.0318  29.478227 -98.563986     602
20        2017-02-18 00:00:00.0      0.0804  29.476374 -98.606411    8338
21        2017-02-18 00:00:00.0      0.0984  29.462273 -98.621473    8578
22        2017-02-18 00:00:00.0      0.0624  29.426854 -98.485875    9280
23        2017-02-18 00:00:00.0      0.0990  29.395531 -98.427387    6929
24        2017-02-18 00:00:00.0      0.1494  29.652697 -98.443906    4922
25        2017-02-18 00:00:00.0      0.1284  29.342793 -98.442748    1738
26        2017-02-18 00:00:00.0      0.0654  29.582046 -98.671928    2349
27        2017-02-18 00:00:00.0      0.1740  29.470899 -98.537179    2135
28        2017-02-18 00:00:00.0      0.1092  29.481882 -98.569293    3771
29        2017-02-18 00:00:00.0      0.0990  29.457811 -98.535803     387
...                         ...         ...        ...        ...     ...
26865722  2017-02-24 17:45:00.0      0.0000  29.455117 -98.494069    4402
26865723  2017-02-24 18:00:00.0      0.0000  29.455117 -98.494069    4402
26865724  2017-02-24 18:15:00.0      0.0000  29.455117 -98.494069    4402
26865725  2017-02-24 18:30:00.0      0.0000  29.455117 -98.494069    4402
26865726  2017-02-24 18:45:00.0      0.0000  29.455117 -98.494069    4402
26865727  2017-02-24 19:00:00.0      0.0000  29.455117 -98.494069    4402
26865728  2017-02-24 19:15:00.0      0.0000  29.455117 -98.494069    4402
26865729  2017-02-24 19:30:00.0      0.0000  29.455117 -98.494069    4402
26865730  2017-02-24 19:45:00.0      0.0000  29.455117 -98.494069    4402
26865731  2017-02-24 20:00:00.0      0.0000  29.455117 -98.494069    4402
26865732  2017-02-24 20:15:00.0      0.0000  29.455117 -98.494069    4402
26865733  2017-02-24 20:30:00.0      0.0000  29.455117 -98.494069    4402
26865734  2017-02-24 20:45:00.0      0.0000  29.455117 -98.494069    4402
26865735  2017-02-24 21:00:00.0      0.0000  29.455117 -98.494069    4402
26865736  2017-02-24 21:15:00.0      0.0000  29.455117 -98.494069    4402
26865737  2017-02-24 21:30:00.0      0.0000  29.455117 -98.494069    4402
26865738  2017-02-24 21:45:00.0      0.0000  29.455117 -98.494069    4402
26865739  2017-02-24 22:00:00.0      0.0000  29.455117 -98.494069    4402
26865740  2017-02-24 22:15:00.0      0.0000  29.455117 -98.494069    4402
26865741  2017-02-24 22:30:00.0      0.0000  29.455117 -98.494069    4402
26865742  2017-02-24 22:45:00.0      0.0000  29.455117 -98.494069    4402
26865743  2017-02-24 23:00:00.0      0.0000  29.455117 -98.494069    4402
26865744  2017-02-24 23:15:00.0      0.0000  29.455117 -98.494069    4402
26865745  2017-02-24 23:30:00.0      0.0000  29.455117 -98.494069    4402
26865746  2017-02-24 23:45:00.0      0.0000  29.455117 -98.494069    4402
26865747  2017-02-24 22:45:00.0      0.2556  29.513850 -98.648098    8692
26865748  2017-02-24 23:00:00.0      0.2844  29.513850 -98.648098    8692
26865749  2017-02-24 23:15:00.0      0.2346  29.513850 -98.648098    8692
26865750  2017-02-24 23:30:00.0      0.2490  29.513850 -98.648098    8692
26865751  2017-02-24 23:45:00.0      0.3204  29.513850 -98.648098    8692

[26865752 rows x 5 columns]

In [10]:
feb17['timestamp'] = feb17['a.local_interval_time']
feb17 = feb17.drop(columns=['a.local_interval_time'])
feb17

          a.lp_value      b.lat     b.long  b.u_id              timestamp
0             0.1794  29.658424 -98.498985    4236  2017-02-18 00:00:00.0
1             0.3000  29.596559 -98.633834    8357  2017-02-18 00:00:00.0
2             0.2046  29.505626 -98.614334    6458  2017-02-18 00:00:00.0
3             0.1290  29.434826 -98.560292    2733  2017-02-18 00:00:00.0
4             0.0768  29.605972 -98.465610    2335  2017-02-18 00:00:00.0
5             0.0222  29.601221 -98.629271    2541  2017-02-18 00:00:00.0
6             0.8682  29.427144 -98.645880    4281  2017-02-18 00:00:00.0
7             0.1872  29.438924 -98.443323    5734  2017-02-18 00:00:00.0
8             0.0834  29.390688 -98.518955    5218  2017-02-18 00:00:00.0
9             0.0858  29.439137 -98.425751    4000  2017-02-18 00:00:00.0
10            0.0018  29.411853 -98.638683    1795  2017-02-18 00:00:00.0
11            0.5922  29.522997 -98.549039    1532  2017-02-18 00:00:00.0
12            0.1866  29.554641 -98.540696    1383  2017-02-18 00:00:00.0
13            0.0480  29.491357 -98.431435    7906  2017-02-18 00:00:00.0
14            0.1512  29.655001 -98.455353    4105  2017-02-18 00:00:00.0
15            0.1416  29.680129 -98.465453    8207  2017-02-18 00:00:00.0
16            0.0234  29.451137 -98.487824     267  2017-02-18 00:00:00.0
17            0.0306  29.508763 -98.486142    6059  2017-02-18 00:00:00.0
18            0.5436  29.354902 -98.421906    2052  2017-02-18 00:00:00.0
19            0.0318  29.478227 -98.563986     602  2017-02-18 00:00:00.0
20            0.0804  29.476374 -98.606411    8338  2017-02-18 00:00:00.0
21            0.0984  29.462273 -98.621473    8578  2017-02-18 00:00:00.0
22            0.0624  29.426854 -98.485875    9280  2017-02-18 00:00:00.0
23            0.0990  29.395531 -98.427387    6929  2017-02-18 00:00:00.0
24            0.1494  29.652697 -98.443906    4922  2017-02-18 00:00:00.0
25            0.1284  29.342793 -98.442748    1738  2017-02-18 00:00:00.0
26            0.0654  29.582046 -98.671928    2349  2017-02-18 00:00:00.0
27            0.1740  29.470899 -98.537179    2135  2017-02-18 00:00:00.0
28            0.1092  29.481882 -98.569293    3771  2017-02-18 00:00:00.0
29            0.0990  29.457811 -98.535803     387  2017-02-18 00:00:00.0
...              ...        ...        ...     ...                    ...
26865722      0.0000  29.455117 -98.494069    4402  2017-02-24 17:45:00.0
26865723      0.0000  29.455117 -98.494069    4402  2017-02-24 18:00:00.0
26865724      0.0000  29.455117 -98.494069    4402  2017-02-24 18:15:00.0
26865725      0.0000  29.455117 -98.494069    4402  2017-02-24 18:30:00.0
26865726      0.0000  29.455117 -98.494069    4402  2017-02-24 18:45:00.0
26865727      0.0000  29.455117 -98.494069    4402  2017-02-24 19:00:00.0
26865728      0.0000  29.455117 -98.494069    4402  2017-02-24 19:15:00.0
26865729      0.0000  29.455117 -98.494069    4402  2017-02-24 19:30:00.0
26865730      0.0000  29.455117 -98.494069    4402  2017-02-24 19:45:00.0
26865731      0.0000  29.455117 -98.494069    4402  2017-02-24 20:00:00.0
26865732      0.0000  29.455117 -98.494069    4402  2017-02-24 20:15:00.0
26865733      0.0000  29.455117 -98.494069    4402  2017-02-24 20:30:00.0
26865734      0.0000  29.455117 -98.494069    4402  2017-02-24 20:45:00.0
26865735      0.0000  29.455117 -98.494069    4402  2017-02-24 21:00:00.0
26865736      0.0000  29.455117 -98.494069    4402  2017-02-24 21:15:00.0
26865737      0.0000  29.455117 -98.494069    4402  2017-02-24 21:30:00.0
26865738      0.0000  29.455117 -98.494069    4402  2017-02-24 21:45:00.0
26865739      0.0000  29.455117 -98.494069    4402  2017-02-24 22:00:00.0
26865740      0.0000  29.455117 -98.494069    4402  2017-02-24 22:15:00.0
26865741      0.0000  29.455117 -98.494069    4402  2017-02-24 22:30:00.0
26865742      0.0000  29.455117 -98.494069    4402  2017-02-24 22:45:00.0
26865743      0.0000  29.455117 -98.494069    4402  2017-02-24 23:00:00.0
26865744      0.0000  29.455117 -98.494069    4402  2017-02-24 23:15:00.0
26865745      0.0000  29.455117 -98.494069    4402  2017-02-24 23:30:00.0
26865746      0.0000  29.455117 -98.494069    4402  2017-02-24 23:45:00.0
26865747      0.2556  29.513850 -98.648098    8692  2017-02-24 22:45:00.0
26865748      0.2844  29.513850 -98.648098    8692  2017-02-24 23:00:00.0
26865749      0.2346  29.513850 -98.648098    8692  2017-02-24 23:15:00.0
26865750      0.2490  29.513850 -98.648098    8692  2017-02-24 23:30:00.0
26865751      0.3204  29.513850 -98.648098    8692  2017-02-24 23:45:00.0

[26865752 rows x 5 columns]

In [11]:
feb17['timestamp'] = pd.to_datetime(feb17['timestamp'])
feb17['lp_value'] = pd.to_numeric(feb17['a.lp_value'])
feb17['Latitude'] = pd.to_numeric(feb17['b.lat'])
feb17['Longitude'] = pd.to_numeric(feb17['b.long'])
feb17['u_id'] = pd.to_numeric(feb17['b.u_id'])
feb17 = feb17.drop(columns=['b.lat', 'b.long', 'a.lp_value', 'b.u_id'])
feb17

                   timestamp  lp_value   Latitude  Longitude  u_id
0        2017-02-18 00:00:00    0.1794  29.658424 -98.498985  4236
1        2017-02-18 00:00:00    0.3000  29.596559 -98.633834  8357
2        2017-02-18 00:00:00    0.2046  29.505626 -98.614334  6458
3        2017-02-18 00:00:00    0.1290  29.434826 -98.560292  2733
4        2017-02-18 00:00:00    0.0768  29.605972 -98.465610  2335
5        2017-02-18 00:00:00    0.0222  29.601221 -98.629271  2541
6        2017-02-18 00:00:00    0.8682  29.427144 -98.645880  4281
7        2017-02-18 00:00:00    0.1872  29.438924 -98.443323  5734
8        2017-02-18 00:00:00    0.0834  29.390688 -98.518955  5218
9        2017-02-18 00:00:00    0.0858  29.439137 -98.425751  4000
10       2017-02-18 00:00:00    0.0018  29.411853 -98.638683  1795
11       2017-02-18 00:00:00    0.5922  29.522997 -98.549039  1532
12       2017-02-18 00:00:00    0.1866  29.554641 -98.540696  1383
13       2017-02-18 00:00:00    0.0480  29.491357 -98.431435  7906
14       2017-02-18 00:00:00    0.1512  29.655001 -98.455353  4105
15       2017-02-18 00:00:00    0.1416  29.680129 -98.465453  8207
16       2017-02-18 00:00:00    0.0234  29.451137 -98.487824   267
17       2017-02-18 00:00:00    0.0306  29.508763 -98.486142  6059
18       2017-02-18 00:00:00    0.5436  29.354902 -98.421906  2052
19       2017-02-18 00:00:00    0.0318  29.478227 -98.563986   602
20       2017-02-18 00:00:00    0.0804  29.476374 -98.606411  8338
21       2017-02-18 00:00:00    0.0984  29.462273 -98.621473  8578
22       2017-02-18 00:00:00    0.0624  29.426854 -98.485875  9280
23       2017-02-18 00:00:00    0.0990  29.395531 -98.427387  6929
24       2017-02-18 00:00:00    0.1494  29.652697 -98.443906  4922
25       2017-02-18 00:00:00    0.1284  29.342793 -98.442748  1738
26       2017-02-18 00:00:00    0.0654  29.582046 -98.671928  2349
27       2017-02-18 00:00:00    0.1740  29.470899 -98.537179  2135
28       2017-02-18 00:00:00    0.1092  29.481882 -98.569293  3771
29       2017-02-18 00:00:00    0.0990  29.457811 -98.535803   387
...                      ...       ...        ...        ...   ...
26865722 2017-02-24 17:45:00    0.0000  29.455117 -98.494069  4402
26865723 2017-02-24 18:00:00    0.0000  29.455117 -98.494069  4402
26865724 2017-02-24 18:15:00    0.0000  29.455117 -98.494069  4402
26865725 2017-02-24 18:30:00    0.0000  29.455117 -98.494069  4402
26865726 2017-02-24 18:45:00    0.0000  29.455117 -98.494069  4402
26865727 2017-02-24 19:00:00    0.0000  29.455117 -98.494069  4402
26865728 2017-02-24 19:15:00    0.0000  29.455117 -98.494069  4402
26865729 2017-02-24 19:30:00    0.0000  29.455117 -98.494069  4402
26865730 2017-02-24 19:45:00    0.0000  29.455117 -98.494069  4402
26865731 2017-02-24 20:00:00    0.0000  29.455117 -98.494069  4402
26865732 2017-02-24 20:15:00    0.0000  29.455117 -98.494069  4402
26865733 2017-02-24 20:30:00    0.0000  29.455117 -98.494069  4402
26865734 2017-02-24 20:45:00    0.0000  29.455117 -98.494069  4402
26865735 2017-02-24 21:00:00    0.0000  29.455117 -98.494069  4402
26865736 2017-02-24 21:15:00    0.0000  29.455117 -98.494069  4402
26865737 2017-02-24 21:30:00    0.0000  29.455117 -98.494069  4402
26865738 2017-02-24 21:45:00    0.0000  29.455117 -98.494069  4402
26865739 2017-02-24 22:00:00    0.0000  29.455117 -98.494069  4402
26865740 2017-02-24 22:15:00    0.0000  29.455117 -98.494069  4402
26865741 2017-02-24 22:30:00    0.0000  29.455117 -98.494069  4402
26865742 2017-02-24 22:45:00    0.0000  29.455117 -98.494069  4402
26865743 2017-02-24 23:00:00    0.0000  29.455117 -98.494069  4402
26865744 2017-02-24 23:15:00    0.0000  29.455117 -98.494069  4402
26865745 2017-02-24 23:30:00    0.0000  29.455117 -98.494069  4402
26865746 2017-02-24 23:45:00    0.0000  29.455117 -98.494069  4402
26865747 2017-02-24 22:45:00    0.2556  29.513850 -98.648098  8692
26865748 2017-02-24 23:00:00    0.2844  29.513850 -98.648098  8692
26865749 2017-02-24 23:15:00    0.2346  29.513850 -98.648098  8692
26865750 2017-02-24 23:30:00    0.2490  29.513850 -98.648098  8692
26865751 2017-02-24 23:45:00    0.3204  29.513850 -98.648098  8692

[26865752 rows x 5 columns]

In [12]:
feb17_prices = pd.merge(prices, feb17, on='timestamp', how='inner')
feb17_prices

,hour,minute,timestamp,price,lp_value,Latitude,Longitude,u_id
0,0.0,15.0,2017-02-01 00:15:00,2.21,0.1152,29.491484,-98.632262,6062
1,0.0,15.0,2017-02-01 00:15:00,2.21,0.0150,29.470405,-98.522710,8537
2,0.0,15.0,2017-02-01 00:15:00,2.21,0.1860,29.738633,-98.647630,139
3,0.0,15.0,2017-02-01 00:15:00,2.21,0.0540,29.491656,-98.550026,9796
4,0.0,15.0,2017-02-01 00:15:00,2.21,0.5976,29.468275,-98.571303,29
5,0.0,15.0,2017-02-01 00:15:00,2.21,0.1476,29.493448,-98.665806,9062
6,0.0,15.0,2017-02-01 00:15:00,2.21,1.0728,29.436254,-98.671223,7719
7,0.0,15.0,2017-02-01 00:15:00,2.21,0.1062,29.534981,-98.374582,7284
8,0.0,15.0,2017-02-01 00:15:00,2.21,0.1434,29.597199,-98.465429,2608
9,0.0,15.0,2017-02-01 00:15:00,2.21,0.0276,29.582046,-98.671928,2349
10,0.0,15.0,2017-02-01 00:15:00,2.21,0.2940,29.465475,-98.618958,9491
11,0.0,15.0,2017-02-01 00:15:00,2.21,0.5688,29.557767,-98.545175,5116
12,0.0,15.0,2017-02-01 00:15:00,2.21,0.1980,29.655603,-98.665760,5875
13,0.0,15.0,2017-02-01 00:15:00,2.21,0.0882,29.369521,-98.624648,1332
14,0.0,15.0,2017-02-01 00:15:00,2.21,0.7698,29.343194,-98.409537,3722
15,0.0,15.0,2017-02-01 00:15:00,2.21,0.5628,29.373916,-98.538687,596
16,0.0,15.0,2017-02-01 00:15:00,2.21,0.1218,29.391129,-98.502665,8859
17,0.0,15.0,2017-02-01 00:15:00,2.21,0.7020,29.446830,-98.515198,1812
18,0.0,15.0,2017-02-01 00:15:00,2.21,0.0216,29.498976,-98.557760,6298
19,0.0,15.0,2017-02-01 00:15:00,2.21,0.6846,29.510418,-98.502845,4571
20,0.0,15.0,2017-02-01 00:15:00,2.21,0.0978,29.476593,-98.656192,6318
21,0.0,15.0,2017-02-01 00:15:00,2.21,1.4208,29.508332,-98.471750,8837
22,0.0,15.0,2017-02-01 00:15:00,2.21,0.1290,29.381355,-98.496036,7024
23,0.0,15.0,2017-02-01 00:15:00,2.21,0.0984,29.556052,-98.677571,6134
24,0.0,15.0,2017-02-01 00:15:00,2.21,0.0456,29.455305,-98.569414,6758
25,0.0,15.0,2017-02-01 00:15:00,2.21,0.5436,29.477009,-98.620411,5922
26,0.0,15.0,2017-02-01 00:15:00,2.21,1.4610,29.425664,-98.410570,9669
27,0.0,15.0,2017-02-01 00:15:00,2.21,0.0180,29.488332,-98.588965,7438
28,0.0,15.0,2017-02-01 00:15:00,2.21,0.2568,29.501891,-98.543952,5496
29,0.0,15.0,2017-02-01 00:15:00,2.21,0.2346,29.534568,-98.712502,5739
...,...,...,...,...,...,...,...,...
26865722,23.0,0.0,2017-02-28 23:00:00,14.78,0.4470,29.415779,-98.482837,4433
26865723,23.0,0.0,2017-02-28 23:00:00,14.78,0.2058,29.432980,-98.557116,7695
26865724,23.0,0.0,2017-02-28 23:00:00,14.78,0.0240,29.444509,-98.467868,4182
26865725,23.0,0.0,2017-02-28 23:00:00,14.78,0.6804,29.520897,-98.733281,1633
26865726,23.0,0.0,2017-02-28 23:00:00,14.78,0.5502,29.678157,-98.462588,2864
26865727,23.0,0.0,2017-02-28 23:00:00,14.78,0.0774,29.365292,-98.426151,7065
26865728,23.0,0.0,2017-02-28 23:00:00,14.78,0.2532,29.356165,-98.521907,6207
26865729,23.0,0.0,2017-02-28 23:00:00,14.78,0.2088,29.335415,-98.473573,2023
26865730,23.0,0.0,2017-02-28 23:00:00,14.78,0.4110,29.503937,-98.647567,5180
26865731,23.0,0.0,2017-02-28 23:00:00,14.78,0.4092,29.343194,-98.409537,3722
26865732,23.0,0.0,2017-02-28 23:00:00,14.78,0.8700,29.684415,-98.476758,4051
26865733,23.0,0.0,2017-02-28 23:00:00,14.78,0.2430,29.481870,-98.604646,1457
26865734,23.0,0.0,2017-02-28 23:00:00,14.78,0.3606,29.638775,-98.612651,3953
26865735,23.0,0.0,2017-02-28 23:00:00,14.78,0.2154,29.472501,-98.596233,4005
26865736,23.0,0.0,2017-02-28 23:00:00,14.78,0.2100,29.412512,-98.603180,3508
26865737,23.0,0.0,2017-02-28 23:00:00,14.78,0.1548,29.661670,-98.461765,6690
26865738,23.0,0.0,2017-02-28 23:00:00,14.78,0.3558,29.510463,-98.585951,5697
26865739,23.0,0.0,2017-02-28 23:00:00,14.78,0.0114,29.572721,-98.608725,4492
26865740,23.0,0.0,2017-02-28 23:00:00,14.78,0.0948,29.638229,-98.421796,2243
26865741,23.0,0.0,2017-02-28 23:00:00,14.78,0.0732,29.492326,-98.624601,6480
26865742,23.0,0.0,2017-02-28 23:00:00,14.78,0.1008,29.419274,-98.487597,9496
26865743,23.0,0.0,2017-02-28 23:00:00,14.78,0.2754,29.518188,-98.814699,7891
26865744,23.0,0.0,2017-02-28 23:00:00,14.78,0.2130,29.329222,-98.561623,9201
26865745,23.0,0.0,2017-02-28 23:00:00,14.78,0.1956,29.398239,-98.441669,5346
26865746,23.0,0.0,2017-02-28 23:00:00,14.78,0.4308,29.415343,-98.449665,1857
26865747,23.0,0.0,2017-02-28 23:00:00,14.78,0.2040,29.533243,-98.790584,337
26865748,23.0,0.0,2017-02-28 23:00:00,14.78,0.0594,29.461789,-98.620087,9077
26865749,23.0,0.0,2017-02-28 23:00:00,14.78,0.0282,29.388935,-98.444855,7840
26865750,23.0,0.0,2017-02-28 23:00:00,14.78,0.2244,29.518135,-98.754062,1722
26865751,23.0,0.0,2017-02-28 23:00:00,14.78,0.2772,29.461651,-98.563531,6756

In [13]:
feb17_prices = feb17_prices.dropna()
feb17_prices = feb17_prices.drop(columns=['hour', 'minute'])
feb17_prices['lp_price'] = feb17_prices['price']*feb17_prices['lp_value']/100
feb17_prices

,timestamp,price,lp_value,Latitude,Longitude,u_id,lp_price
0,2017-02-01 00:15:00,2.21,0.1152,29.491484,-98.632262,6062,0.002546
1,2017-02-01 00:15:00,2.21,0.0150,29.470405,-98.522710,8537,0.000331
2,2017-02-01 00:15:00,2.21,0.1860,29.738633,-98.647630,139,0.004111
3,2017-02-01 00:15:00,2.21,0.0540,29.491656,-98.550026,9796,0.001193
4,2017-02-01 00:15:00,2.21,0.5976,29.468275,-98.571303,29,0.013207
5,2017-02-01 00:15:00,2.21,0.1476,29.493448,-98.665806,9062,0.003262
6,2017-02-01 00:15:00,2.21,1.0728,29.436254,-98.671223,7719,0.023709
7,2017-02-01 00:15:00,2.21,0.1062,29.534981,-98.374582,7284,0.002347
8,2017-02-01 00:15:00,2.21,0.1434,29.597199,-98.465429,2608,0.003169
9,2017-02-01 00:15:00,2.21,0.0276,29.582046,-98.671928,2349,0.000610
10,2017-02-01 00:15:00,2.21,0.2940,29.465475,-98.618958,9491,0.006497
11,2017-02-01 00:15:00,2.21,0.5688,29.557767,-98.545175,5116,0.012570
12,2017-02-01 00:15:00,2.21,0.1980,29.655603,-98.665760,5875,0.004376
13,2017-02-01 00:15:00,2.21,0.0882,29.369521,-98.624648,1332,0.001949
14,2017-02-01 00:15:00,2.21,0.7698,29.343194,-98.409537,3722,0.017013
15,2017-02-01 00:15:00,2.21,0.5628,29.373916,-98.538687,596,0.012438
16,2017-02-01 00:15:00,2.21,0.1218,29.391129,-98.502665,8859,0.002692
17,2017-02-01 00:15:00,2.21,0.7020,29.446830,-98.515198,1812,0.015514
18,2017-02-01 00:15:00,2.21,0.0216,29.498976,-98.557760,6298,0.000477
19,2017-02-01 00:15:00,2.21,0.6846,29.510418,-98.502845,4571,0.015130
20,2017-02-01 00:15:00,2.21,0.0978,29.476593,-98.656192,6318,0.002161
21,2017-02-01 00:15:00,2.21,1.4208,29.508332,-98.471750,8837,0.031400
22,2017-02-01 00:15:00,2.21,0.1290,29.381355,-98.496036,7024,0.002851
23,2017-02-01 00:15:00,2.21,0.0984,29.556052,-98.677571,6134,0.002175
24,2017-02-01 00:15:00,2.21,0.0456,29.455305,-98.569414,6758,0.001008
25,2017-02-01 00:15:00,2.21,0.5436,29.477009,-98.620411,5922,0.012014
26,2017-02-01 00:15:00,2.21,1.4610,29.425664,-98.410570,9669,0.032288
27,2017-02-01 00:15:00,2.21,0.0180,29.488332,-98.588965,7438,0.000398
28,2017-02-01 00:15:00,2.21,0.2568,29.501891,-98.543952,5496,0.005675
29,2017-02-01 00:15:00,2.21,0.2346,29.534568,-98.712502,5739,0.005185
...,...,...,...,...,...,...,...
26865722,2017-02-28 23:00:00,14.78,0.4470,29.415779,-98.482837,4433,0.066067
26865723,2017-02-28 23:00:00,14.78,0.2058,29.432980,-98.557116,7695,0.030417
26865724,2017-02-28 23:00:00,14.78,0.0240,29.444509,-98.467868,4182,0.003547
26865725,2017-02-28 23:00:00,14.78,0.6804,29.520897,-98.733281,1633,0.100563
26865726,2017-02-28 23:00:00,14.78,0.5502,29.678157,-98.462588,2864,0.081320
26865727,2017-02-28 23:00:00,14.78,0.0774,29.365292,-98.426151,7065,0.011440
26865728,2017-02-28 23:00:00,14.78,0.2532,29.356165,-98.521907,6207,0.037423
26865729,2017-02-28 23:00:00,14.78,0.2088,29.335415,-98.473573,2023,0.030861
26865730,2017-02-28 23:00:00,14.78,0.4110,29.503937,-98.647567,5180,0.060746
26865731,2017-02-28 23:00:00,14.78,0.4092,29.343194,-98.409537,3722,0.060480
26865732,2017-02-28 23:00:00,14.78,0.8700,29.684415,-98.476758,4051,0.128586
26865733,2017-02-28 23:00:00,14.78,0.2430,29.481870,-98.604646,1457,0.035915
26865734,2017-02-28 23:00:00,14.78,0.3606,29.638775,-98.612651,3953,0.053297
26865735,2017-02-28 23:00:00,14.78,0.2154,29.472501,-98.596233,4005,0.031836
26865736,2017-02-28 23:00:00,14.78,0.2100,29.412512,-98.603180,3508,0.031038
26865737,2017-02-28 23:00:00,14.78,0.1548,29.661670,-98.461765,6690,0.022879
26865738,2017-02-28 23:00:00,14.78,0.3558,29.510463,-98.585951,5697,0.052587
26865739,2017-02-28 23:00:00,14.78,0.0114,29.572721,-98.608725,4492,0.001685
26865740,2017-02-28 23:00:00,14.78,0.0948,29.638229,-98.421796,2243,0.014011
26865741,2017-02-28 23:00:00,14.78,0.0732,29.492326,-98.624601,6480,0.010819
26865742,2017-02-28 23:00:00,14.78,0.1008,29.419274,-98.487597,9496,0.014898
26865743,2017-02-28 23:00:00,14.78,0.2754,29.518188,-98.814699,7891,0.040704
26865744,2017-02-28 23:00:00,14.78,0.2130,29.329222,-98.561623,9201,0.031481
26865745,2017-02-28 23:00:00,14.78,0.1956,29.398239,-98.441669,5346,0.028910
26865746,2017-02-28 23:00:00,14.78,0.4308,29.415343,-98.449665,1857,0.063672
26865747,2017-02-28 23:00:00,14.78,0.2040,29.533243,-98.790584,337,0.030151
26865748,2017-02-28 23:00:00,14.78,0.0594,29.461789,-98.620087,9077,0.008779
26865749,2017-02-28 23:00:00,14.78,0.0282,29.388935,-98.444855,7840,0.004168
26865750,2017-02-28 23:00:00,14.78,0.2244,29.518135,-98.754062,1722,0.033166
26865751,2017-02-28 23:00:00,14.78,0.2772,29.461651,-98.563531,6756,0.040970

In [14]:
consumption = feb17_prices.groupby('u_id').sum()

In [15]:
consumption = consumption.drop(columns=['price', 'lp_value', 'Longitude', 'Latitude'])
consumption

         lp_price
u_id
1      180.467883
2      172.102982
3      108.606115
4      294.966236
5       31.561870
6      162.730685
7      209.560280
8      133.613831
9       95.427107
10      68.617150
11      99.633906
12      97.144531
13      72.245771
14      91.761522
15     147.455802
16      53.357542
17       2.090909
18      76.350072
19     236.445742
20     113.281847
21     105.346726
22       2.979230
23     170.569553
24     116.026680
25      53.246914
26      48.179315
27     298.785617
28     159.999668
29     130.365469
30      82.321555
...           ...
9971   184.868909
9972   126.719700
9973    71.291270
9974   163.474217
9975   357.573247
9976   151.014670
9977    39.371524
9978   125.723195
9979   156.266942
9980   260.693735
9981    92.510099
9982   100.710387
9983   173.548280
9984    86.779750
9985   385.781521
9986   128.488213
9987   318.078365
9988   251.034427
9989    75.010301
9990    94.661652
9991   348.748108
9992   144.412477
9993   264.904505
9994   391.502816
9995   160.045567
9996   128.766986
9997   123.681636
9998   184.312028
9999    25.452762
10000  276.748499

[9975 rows x 1 columns]

In [16]:
address = pd.read_csv('address.csv')
address

,Unnamed: 0,Latitude,Longitude,u_id,Address
0,0,29.658424,-98.498985,4236,"23411 Hardy Oak Blvd, San Antonio, TX 78258, USA"
1,1,29.596559,-98.633834,8357,"7408 Hummingbird Hill Ln, San Antonio, TX 7825..."
2,2,29.505626,-98.614334,6458,"6537 Trotter Ln, San Antonio, TX 78240, USA"
3,3,29.434826,-98.560292,2733,"210 N San Horacio Ave, San Antonio, TX 78237, USA"
4,4,29.605972,-98.465610,2335,"1754 N Loop 1604 E, San Antonio, TX 78232, USA"
5,5,29.601221,-98.629271,2541,"17865 Babcock Rd, San Antonio, TX 78255, USA"
6,6,29.427144,-98.645880,4281,"7456 Timbercreek Dr, San Antonio, TX 78227, USA"
7,7,29.438924,-98.443323,5734,"2922 N PanAm Expy, San Antonio, TX 78208, USA"
8,8,29.390688,-98.518955,5218,"203 Nunes St, San Antonio, TX 78225, USA"
9,9,29.439137,-98.425751,4000,"Belgium Opposite Rossolis, San Antonio, TX 782..."
10,10,29.411853,-98.638683,1795,"2007 Hackamore Ln, San Antonio, TX 78227, USA"
11,11,29.522997,-98.549039,1532,"3253 Swandale St, San Antonio, TX 78230, USA"
12,12,29.554641,-98.540696,1383,"82 Turnberry Way, San Antonio, TX 78230, USA"
13,13,29.491357,-98.431435,7906,"2620 Harry Wurzbach Rd, San Antonio, TX 78209,..."
14,14,29.655001,-98.455353,4105,"Unnamed Road, San Antonio, TX 78258, USA"
15,15,29.680129,-98.465453,8207,"25519 Little Brook, San Antonio, TX 78260, USA"
16,16,29.451137,-98.487824,267,"2727 N St Mary's St, San Antonio, TX 78212, USA"
17,17,29.508763,-98.486142,6059,"407 Springwood Ln, San Antonio, TX 78216, USA"
18,18,29.354902,-98.421906,2052,"3735 SE Military Dr, San Antonio, TX 78223, USA"
19,19,29.478227,-98.563986,602,"107 Inspiration Dr, San Antonio, TX 78228, USA"
20,20,29.476374,-98.606411,8338,"4507 Warpath St, San Antonio, TX 78238, USA"
21,21,29.462273,-98.621473,8578,"Fairgrounds & NW Loop 410N Access Rd, San Anto..."
22,22,29.426854,-98.485875,9280,"170 Ave E, San Antonio, TX 78205, USA"
23,23,29.395531,-98.427387,6929,"2529 Amity Rd, San Antonio, TX 78210, USA"
24,24,29.652697,-98.443906,4922,"2610 TPC Pkwy, San Antonio, TX 78259, USA"
25,25,29.342793,-98.442748,1738,"8019 S New Braunfels Ave, San Antonio, TX 7823..."
26,26,29.582046,-98.671928,2349,"14901 Seven L Trail, Helotes, TX 78023, USA"
27,27,29.470899,-98.537179,2135,"2 Cromwell Dr, San Antonio, TX 78201, USA"
28,28,29.481882,-98.569293,3771,"4307 North Westberry Drive, San Antonio, TX 78..."
29,29,29.457811,-98.535803,387,"2211 W Magnolia Ave, San Antonio, TX 78201, USA"
...,...,...,...,...,...
9945,9945,29.389037,-98.534936,1711,"721 Hearne Ave, San Antonio, TX 78225, USA"
9946,9946,29.378766,-98.477278,7810,"100 Llano St, San Antonio, TX 78223, USA"
9947,9947,29.481948,-98.690708,4458,"2 Impala Smt, San Antonio, TX 78251, USA"
9948,9948,29.396060,-98.458088,6857,"1226 E Highland Blvd, San Antonio, TX 78210, USA"
9949,9949,29.432843,-98.762015,2455,"3074 Rolling Grv, San Antonio, TX 78253, USA"
9950,9950,29.616109,-98.586483,2542,"Far North Central, San Antonio, TX, USA"
9951,9951,29.553098,-98.515277,3094,"12301 Blanco Rd, San Antonio, TX 78216, USA"
9952,9952,29.673357,-98.637993,8172,"7902 Calle Rialto Suite 200, San Antonio, TX 7..."
9953,9953,29.478927,-98.437928,5578,"209 Lyman Dr, San Antonio, TX 78209, USA"
9954,9954,29.596330,-98.460280,8946,"16723 Parkstone Blvd, San Antonio, TX 78232, USA"
9955,9955,29.363815,-98.496751,5257,"205 W Huff Ave, San Antonio, TX 78214, USA"
9956,9956,29.483878,-98.510645,2115,"919 Lovera Blvd, San Antonio, TX 78201, USA"
9957,9957,29.573757,-98.643123,6548,"8000 TX-1604 Loop, San Antonio, TX 78249, USA"
9958,9958,29.511105,-98.693901,278,"7443 Alverstone Way, San Antonio, TX 78250, USA"
9959,9959,29.490542,-98.367002,7481,"4815 Castle Pine, San Antonio, TX 78218, USA"
9960,9960,29.501022,-98.542883,608,"315 Sullivan Dr, San Antonio, TX 78213, USA"
9961,9961,29.405417,-98.468080,3871,"Porter & Piedmont, San Antonio, TX 78210, USA"
9962,9962,29.395904,-98.639730,4334,"15540 782239740, 181 South St, San Antonio, TX..."
9963,9963,29.425104,-98.662046,8627,"9011 Gull Lake, San Antonio, TX 78245, USA"
9964,9964,29.474702,-98.683820,7417,"9811 Kerrville St, San Antonio, TX 78251, USA"
9965,9965,29.503509,-98.577340,7880,"4502 Medical Dr, San Antonio, TX 78229, USA"
9966,9966,29.458686,-98.502172,2912,"531 West Summit, San Antonio, TX 78212, USA"
9967,9967,29.511266,-98.509884,5389,"517 Antler Dr, San Antonio, TX 78213, USA"
9968,9968,29.665016,-98.649559,8994,"8500 Cross Mountain Trail, San Antonio, TX 782..."
9969,9969,29.356533,-98.506645,2791,"910 SW Military Dr, San Antonio, TX 78221, USA"
9970,9970,29.523236,-98.586117,2034,"8820 Breezefield, San Antonio, TX 78240, USA"
9971,9971,29.352700,-98.583503,8889,"Hidden Cove - Indian Creek, San Antonio, TX, USA"
9972,9972,29.508917,-98.567106,1134,"7718 Pasteur Ct, San Antonio, TX 78229, USA"
9973,9973,29.351592,-98.514514,8690,"709 Burton Ave, San Antonio, TX 78221, USA"
9974,9974,29.392712,-98.436946,4487,"1751 Amanda St, San Antonio, TX 78210, USA"

In [17]:
address.set_index('u_id', inplace=True)

In [18]:
address

,Unnamed: 0,Latitude,Longitude,Address
u_id,,,,
4236,0,29.658424,-98.498985,"23411 Hardy Oak Blvd, San Antonio, TX 78258, USA"
8357,1,29.596559,-98.633834,"7408 Hummingbird Hill Ln, San Antonio, TX 7825..."
6458,2,29.505626,-98.614334,"6537 Trotter Ln, San Antonio, TX 78240, USA"
2733,3,29.434826,-98.560292,"210 N San Horacio Ave, San Antonio, TX 78237, USA"
2335,4,29.605972,-98.465610,"1754 N Loop 1604 E, San Antonio, TX 78232, USA"
2541,5,29.601221,-98.629271,"17865 Babcock Rd, San Antonio, TX 78255, USA"
4281,6,29.427144,-98.645880,"7456 Timbercreek Dr, San Antonio, TX 78227, USA"
5734,7,29.438924,-98.443323,"2922 N PanAm Expy, San Antonio, TX 78208, USA"
5218,8,29.390688,-98.518955,"203 Nunes St, San Antonio, TX 78225, USA"
4000,9,29.439137,-98.425751,"Belgium Opposite Rossolis, San Antonio, TX 782..."
1795,10,29.411853,-98.638683,"2007 Hackamore Ln, San Antonio, TX 78227, USA"
1532,11,29.522997,-98.549039,"3253 Swandale St, San Antonio, TX 78230, USA"
1383,12,29.554641,-98.540696,"82 Turnberry Way, San Antonio, TX 78230, USA"
7906,13,29.491357,-98.431435,"2620 Harry Wurzbach Rd, San Antonio, TX 78209,..."
4105,14,29.655001,-98.455353,"Unnamed Road, San Antonio, TX 78258, USA"
8207,15,29.680129,-98.465453,"25519 Little Brook, San Antonio, TX 78260, USA"
267,16,29.451137,-98.487824,"2727 N St Mary's St, San Antonio, TX 78212, USA"
6059,17,29.508763,-98.486142,"407 Springwood Ln, San Antonio, TX 78216, USA"
2052,18,29.354902,-98.421906,"3735 SE Military Dr, San Antonio, TX 78223, USA"
602,19,29.478227,-98.563986,"107 Inspiration Dr, San Antonio, TX 78228, USA"
8338,20,29.476374,-98.606411,"4507 Warpath St, San Antonio, TX 78238, USA"
8578,21,29.462273,-98.621473,"Fairgrounds & NW Loop 410N Access Rd, San Anto..."
9280,22,29.426854,-98.485875,"170 Ave E, San Antonio, TX 78205, USA"
6929,23,29.395531,-98.427387,"2529 Amity Rd, San Antonio, TX 78210, USA"
4922,24,29.652697,-98.443906,"2610 TPC Pkwy, San Antonio, TX 78259, USA"
1738,25,29.342793,-98.442748,"8019 S New Braunfels Ave, San Antonio, TX 7823..."
2349,26,29.582046,-98.671928,"14901 Seven L Trail, Helotes, TX 78023, USA"
2135,27,29.470899,-98.537179,"2 Cromwell Dr, San Antonio, TX 78201, USA"
3771,28,29.481882,-98.569293,"4307 North Westberry Drive, San Antonio, TX 78..."
387,29,29.457811,-98.535803,"2211 W Magnolia Ave, San Antonio, TX 78201, USA"
...,...,...,...,...
1711,9945,29.389037,-98.534936,"721 Hearne Ave, San Antonio, TX 78225, USA"
7810,9946,29.378766,-98.477278,"100 Llano St, San Antonio, TX 78223, USA"
4458,9947,29.481948,-98.690708,"2 Impala Smt, San Antonio, TX 78251, USA"
6857,9948,29.396060,-98.458088,"1226 E Highland Blvd, San Antonio, TX 78210, USA"
2455,9949,29.432843,-98.762015,"3074 Rolling Grv, San Antonio, TX 78253, USA"
2542,9950,29.616109,-98.586483,"Far North Central, San Antonio, TX, USA"
3094,9951,29.553098,-98.515277,"12301 Blanco Rd, San Antonio, TX 78216, USA"
8172,9952,29.673357,-98.637993,"7902 Calle Rialto Suite 200, San Antonio, TX 7..."
5578,9953,29.478927,-98.437928,"209 Lyman Dr, San Antonio, TX 78209, USA"
8946,9954,29.596330,-98.460280,"16723 Parkstone Blvd, San Antonio, TX 78232, USA"
5257,9955,29.363815,-98.496751,"205 W Huff Ave, San Antonio, TX 78214, USA"
2115,9956,29.483878,-98.510645,"919 Lovera Blvd, San Antonio, TX 78201, USA"
6548,9957,29.573757,-98.643123,"8000 TX-1604 Loop, San Antonio, TX 78249, USA"
278,9958,29.511105,-98.693901,"7443 Alverstone Way, San Antonio, TX 78250, USA"
7481,9959,29.490542,-98.367002,"4815 Castle Pine, San Antonio, TX 78218, USA"
608,9960,29.501022,-98.542883,"315 Sullivan Dr, San Antonio, TX 78213, USA"
3871,9961,29.405417,-98.468080,"Porter & Piedmont, San Antonio, TX 78210, USA"
4334,9962,29.395904,-98.639730,"15540 782239740, 181 South St, San Antonio, TX..."
8627,9963,29.425104,-98.662046,"9011 Gull Lake, San Antonio, TX 78245, USA"
7417,9964,29.474702,-98.683820,"9811 Kerrville St, San Antonio, TX 78251, USA"
7880,9965,29.503509,-98.577340,"4502 Medical Dr, San Antonio, TX 78229, USA"
2912,9966,29.458686,-98.502172,"531 West Summit, San Antonio, TX 78212, USA"
5389,9967,29.511266,-98.509884,"517 Antler Dr, San Antonio, TX 78213, USA"
8994,9968,29.665016,-98.649559,"8500 Cross Mountain Trail, San Antonio, TX 782..."
2791,9969,29.356533,-98.506645,"910 SW Military Dr, San Antonio, TX 78221, USA"
2034,9970,29.523236,-98.586117,"8820 Breezefield, San Antonio, TX 78240, USA"
8889,9971,29.352700,-98.583503,"Hidden Cove - Indian Creek, San Antonio, TX, USA"
1134,9972,29.508917,-98.567106,"7718 Pasteur Ct, San Antonio, TX 78229, USA"
8690,9973,29.351592,-98.514514,"709 Burton Ave, San Antonio, TX 78221, USA"
4487,9974,29.392712,-98.436946,"1751 Amanda St, San Antonio, TX 78210, USA"

In [19]:
address.columns

Index(['Unnamed: 0', 'Latitude', 'Longitude', 'Address'], dtype='object')

In [20]:
house_consumption = pd.merge(consumption, address, on=['u_id'], how='inner')
house_consumption

,lp_price,Unnamed: 0,Latitude,Longitude,Address
u_id,,,,,
1,180.467883,2224,29.595073,-98.494584,"3 Village Knoll, San Antonio, TX 78232, USA"
2,172.102982,6589,29.420675,-98.544263,"1007 NW 24th St, San Antonio, TX 78207, USA"
3,108.606115,175,29.502078,-98.255201,"Pvt Rd, Schertz, TX 78154, USA"
4,294.966236,2663,29.625522,-98.704066,"Helotes, TX 78023, USA"
5,31.561870,4408,29.427540,-98.492764,"102 E Travis St, San Antonio, TX 78205, USA"
6,162.730685,753,29.455852,-98.561336,"515 Marquette Dr, San Antonio, TX 78228, USA"
7,209.560280,2819,29.480186,-98.293570,"TX-1604 Loop, Schertz, TX 78154, USA"
8,133.613831,9289,29.465277,-98.567047,"4119 Willard Dr, San Antonio, TX 78228, USA"
9,95.427107,3985,29.427322,-98.495210,"217 W Travis St, San Antonio, TX 78205, USA"
10,68.617150,2219,29.489916,-98.595940,"6259 Cairo Dr, San Antonio, TX 78229, USA"
11,99.633906,1348,29.569105,-98.656782,"14030 Farm to Market Rd 1560, Helotes, TX 7802..."
12,97.144531,3608,29.476957,-98.341141,"7511 Woodlake View, San Antonio, TX 78244, USA"
13,72.245771,7186,29.439896,-98.818265,"290 Co Rd 386, San Antonio, TX 78253, USA"
14,91.761522,8289,29.427725,-98.531613,"Buena Vista & Hamilton, San Antonio, TX 78207,..."
15,147.455802,5846,29.488665,-98.575151,"6123 Callaghan Rd, San Antonio, TX 78228, USA"
16,53.357542,5417,29.437217,-98.560265,"303 N San Horacio Ave, San Antonio, TX 78237, USA"
17,2.090909,3433,29.447580,-98.538292,"1715 Kentucky Ave, San Antonio, TX 78201, USA"
18,76.350072,2279,29.468404,-98.668108,"9740 Raba Dr, San Antonio, TX 78251, USA"
19,236.445742,2844,29.470285,-98.655242,"2948 Wood Cir, San Antonio, TX 78251, USA"
20,113.281847,664,29.462827,-98.752129,"12814 Braxon Pass, San Antonio, TX 78253, USA"
21,105.346726,3938,29.445597,-98.546107,"2717 Lombrano St, San Antonio, TX 78228, USA"
22,2.979230,8288,29.609925,-98.500727,"901 Texas 1604 Access Rd, San Antonio, TX 7825..."
23,170.569553,1786,29.522367,-98.755573,"13012 Galm Rd, San Antonio, TX 78254, USA"
24,116.026680,6120,29.324165,-98.542070,"1400 W Villaret Blvd, San Antonio, TX 78224, USA"
25,53.246914,1290,29.449514,-98.476070,"2549 Avenue B, San Antonio, TX 78215, USA"
26,48.179315,7409,29.599719,-98.478136,"232 Donella Dr, Hollywood Park, TX 78232, USA"
27,298.785617,2564,29.491130,-98.427037,"6903 S Sunbelt Dr, San Antonio, TX 78218, USA"
28,159.999668,7054,29.470540,-98.364381,"4714 Juniper Farm, San Antonio, TX 78244, USA"
29,130.365469,226,29.468275,-98.571303,"1494 Hillcrest Dr, San Antonio, TX 78228, USA"
30,82.321555,9737,29.663871,-98.457583,"2121 Oakland Bend, San Antonio, TX 78258, USA"
...,...,...,...,...,...
9971,184.868909,5126,29.338686,-98.493000,"392 E Petaluma Blvd, San Antonio, TX 78221, USA"
9972,126.719700,9228,29.427959,-98.640994,"798 Valley Center Dr, San Antonio, TX 78227, USA"
9973,71.291270,5365,29.403303,-98.483826,"1246 S Hackberry St, San Antonio, TX 78210, USA"
9974,163.474217,5080,29.513568,-98.661833,"7723 Tezel Rd, San Antonio, TX 78250, USA"
9975,357.573247,4282,29.465858,-98.823948,"1670 Co Rd 381, San Antonio, TX 78253, USA"
9976,151.014670,331,29.427946,-98.679692,"942 Hayloft Ln, San Antonio, TX 78245, USA"
9977,39.371524,1003,29.334757,-98.414381,"San Antonio, TX 78222, USA"
9978,125.723195,7693,29.537430,-98.696577,"10109 Chariot Trail, San Antonio, TX 78254, USA"
9979,156.266942,2457,29.615807,-98.514450,"18903 Windsor Wood, San Antonio, TX 78258, USA"
9980,260.693735,5703,29.514334,-98.720224,"8098 Stalemate Cove, San Antonio, TX 78254, USA"
9981,92.510099,9464,29.387712,-98.468458,"391 Astor St, San Antonio, TX 78210, USA"
9982,100.710387,6483,29.381814,-98.491339,"1515 Mission Rd, San Antonio, TX 78210, USA"
9983,173.548280,2886,29.676763,-98.482325,"25319 Battle Lake, San Antonio, TX 78260, USA"
9984,86.779750,7898,29.532497,-98.710805,"11123 Buckskin Bend, San Antonio, TX 78254, USA"
9985,385.781521,7356,29.615811,-98.491808,"158 E Sonterra Blvd #102, San Antonio, TX 7825..."
9986,128.488213,3702,29.496554,-98.421476,"3833 Eisenhauer Rd, San Antonio, TX 78218, USA"
9987,318.078365,9893,29.557866,-98.692747,"Helotes, TX 78023, USA"
9988,251.034427,6190,29.432878,-98.732053,"11937 FM1957, San Antonio, TX 78253, USA"
9989,75.010301,9021,29.582829,-98.596653,"15447 Frontage Rd, San Antonio, TX 78249, USA"
9990,94.661652,8892,29.466608,-98.501041,"447 W Hildebrand Ave, San Antonio, TX 78212, USA"
9991,348.748108,2063,29.348759,-98.627664,"6226 Wild Valley Dr, San Antonio, TX 78242, USA"
9992,144.412477,1019,29.574536,-98.614972,"San Antonio, TX 78249, USA"
9993,264.904505,6305,29.448065,-98.674345,"San Antonio, TX 78251, USA"
9994,391.502816,4958,29.672531,-98.497688,"206 Red Willow, San Antonio, TX 78260, USA"
9995,160.045567,8463,29.483561,-98.552766,"339 Glenarm Pl, Balcones Heights, TX 78201, USA"
9996,128.766986,157,29.603970,-98.520226,"42 Imperial Way, San Antonio, TX 78248, USA"
9997,123.681636,5341,29.651936,-98.629053,"505 Cypress Trail, San Antonio, TX 78256, USA"
9998,184.312028,5583,29.562076,-98.518604,"Blanco Opp Phil Hardberger Park, San Antonio, ..."
9999,25.452762,4621,29.520738,-98.702787,"10703 Judie Allen, San Antonio, TX 78254, USA"
10000,276.748499,9673,29.499816,-98.364760,"7410 Monets Garden, San Antonio, TX 78218, USA"

In [21]:
house_consumption = house_consumption.drop(columns=['Unnamed: 0'])
house_consumption

,lp_price,Latitude,Longitude,Address
u_id,,,,
1,180.467883,29.595073,-98.494584,"3 Village Knoll, San Antonio, TX 78232, USA"
2,172.102982,29.420675,-98.544263,"1007 NW 24th St, San Antonio, TX 78207, USA"
3,108.606115,29.502078,-98.255201,"Pvt Rd, Schertz, TX 78154, USA"
4,294.966236,29.625522,-98.704066,"Helotes, TX 78023, USA"
5,31.561870,29.427540,-98.492764,"102 E Travis St, San Antonio, TX 78205, USA"
6,162.730685,29.455852,-98.561336,"515 Marquette Dr, San Antonio, TX 78228, USA"
7,209.560280,29.480186,-98.293570,"TX-1604 Loop, Schertz, TX 78154, USA"
8,133.613831,29.465277,-98.567047,"4119 Willard Dr, San Antonio, TX 78228, USA"
9,95.427107,29.427322,-98.495210,"217 W Travis St, San Antonio, TX 78205, USA"
10,68.617150,29.489916,-98.595940,"6259 Cairo Dr, San Antonio, TX 78229, USA"
11,99.633906,29.569105,-98.656782,"14030 Farm to Market Rd 1560, Helotes, TX 7802..."
12,97.144531,29.476957,-98.341141,"7511 Woodlake View, San Antonio, TX 78244, USA"
13,72.245771,29.439896,-98.818265,"290 Co Rd 386, San Antonio, TX 78253, USA"
14,91.761522,29.427725,-98.531613,"Buena Vista & Hamilton, San Antonio, TX 78207,..."
15,147.455802,29.488665,-98.575151,"6123 Callaghan Rd, San Antonio, TX 78228, USA"
16,53.357542,29.437217,-98.560265,"303 N San Horacio Ave, San Antonio, TX 78237, USA"
17,2.090909,29.447580,-98.538292,"1715 Kentucky Ave, San Antonio, TX 78201, USA"
18,76.350072,29.468404,-98.668108,"9740 Raba Dr, San Antonio, TX 78251, USA"
19,236.445742,29.470285,-98.655242,"2948 Wood Cir, San Antonio, TX 78251, USA"
20,113.281847,29.462827,-98.752129,"12814 Braxon Pass, San Antonio, TX 78253, USA"
21,105.346726,29.445597,-98.546107,"2717 Lombrano St, San Antonio, TX 78228, USA"
22,2.979230,29.609925,-98.500727,"901 Texas 1604 Access Rd, San Antonio, TX 7825..."
23,170.569553,29.522367,-98.755573,"13012 Galm Rd, San Antonio, TX 78254, USA"
24,116.026680,29.324165,-98.542070,"1400 W Villaret Blvd, San Antonio, TX 78224, USA"
25,53.246914,29.449514,-98.476070,"2549 Avenue B, San Antonio, TX 78215, USA"
26,48.179315,29.599719,-98.478136,"232 Donella Dr, Hollywood Park, TX 78232, USA"
27,298.785617,29.491130,-98.427037,"6903 S Sunbelt Dr, San Antonio, TX 78218, USA"
28,159.999668,29.470540,-98.364381,"4714 Juniper Farm, San Antonio, TX 78244, USA"
29,130.365469,29.468275,-98.571303,"1494 Hillcrest Dr, San Antonio, TX 78228, USA"
30,82.321555,29.663871,-98.457583,"2121 Oakland Bend, San Antonio, TX 78258, USA"
...,...,...,...,...
9971,184.868909,29.338686,-98.493000,"392 E Petaluma Blvd, San Antonio, TX 78221, USA"
9972,126.719700,29.427959,-98.640994,"798 Valley Center Dr, San Antonio, TX 78227, USA"
9973,71.291270,29.403303,-98.483826,"1246 S Hackberry St, San Antonio, TX 78210, USA"
9974,163.474217,29.513568,-98.661833,"7723 Tezel Rd, San Antonio, TX 78250, USA"
9975,357.573247,29.465858,-98.823948,"1670 Co Rd 381, San Antonio, TX 78253, USA"
9976,151.014670,29.427946,-98.679692,"942 Hayloft Ln, San Antonio, TX 78245, USA"
9977,39.371524,29.334757,-98.414381,"San Antonio, TX 78222, USA"
9978,125.723195,29.537430,-98.696577,"10109 Chariot Trail, San Antonio, TX 78254, USA"
9979,156.266942,29.615807,-98.514450,"18903 Windsor Wood, San Antonio, TX 78258, USA"
9980,260.693735,29.514334,-98.720224,"8098 Stalemate Cove, San Antonio, TX 78254, USA"
9981,92.510099,29.387712,-98.468458,"391 Astor St, San Antonio, TX 78210, USA"
9982,100.710387,29.381814,-98.491339,"1515 Mission Rd, San Antonio, TX 78210, USA"
9983,173.548280,29.676763,-98.482325,"25319 Battle Lake, San Antonio, TX 78260, USA"
9984,86.779750,29.532497,-98.710805,"11123 Buckskin Bend, San Antonio, TX 78254, USA"
9985,385.781521,29.615811,-98.491808,"158 E Sonterra Blvd #102, San Antonio, TX 7825..."
9986,128.488213,29.496554,-98.421476,"3833 Eisenhauer Rd, San Antonio, TX 78218, USA"
9987,318.078365,29.557866,-98.692747,"Helotes, TX 78023, USA"
9988,251.034427,29.432878,-98.732053,"11937 FM1957, San Antonio, TX 78253, USA"
9989,75.010301,29.582829,-98.596653,"15447 Frontage Rd, San Antonio, TX 78249, USA"
9990,94.661652,29.466608,-98.501041,"447 W Hildebrand Ave, San Antonio, TX 78212, USA"
9991,348.748108,29.348759,-98.627664,"6226 Wild Valley Dr, San Antonio, TX 78242, USA"
9992,144.412477,29.574536,-98.614972,"San Antonio, TX 78249, USA"
9993,264.904505,29.448065,-98.674345,"San Antonio, TX 78251, USA"
9994,391.502816,29.672531,-98.497688,"206 Red Willow, San Antonio, TX 78260, USA"
9995,160.045567,29.483561,-98.552766,"339 Glenarm Pl, Balcones Heights, TX 78201, USA"
9996,128.766986,29.603970,-98.520226,"42 Imperial Way, San Antonio, TX 78248, USA"
9997,123.681636,29.651936,-98.629053,"505 Cypress Trail, San Antonio, TX 78256, USA"
9998,184.312028,29.562076,-98.518604,"Blanco Opp Phil Hardberger Park, San Antonio, ..."
9999,25.452762,29.520738,-98.702787,"10703 Judie Allen, San Antonio, TX 78254, USA"
10000,276.748499,29.499816,-98.364760,"7410 Monets Garden, San Antonio, TX 78218, USA"

In [22]:
house_consumption.to_csv('feb17_house_consumption.csv')

In [23]:
house_consumption['lp_price'].describe()

count    9975.000000
mean      146.272191
std       148.553349
min         0.000000
25%        77.741029
50%       124.523797
75%       186.361897
max      7446.167231
Name: lp_price, dtype: float64

In [1]:
import pandas as pd
address = pd.read_csv('address.csv')
add = pd.read_csv('PropertySearchResults - BCAD.csv')

In [4]:
add.rename(columns={'Property Address':'Address'}, inplace=True)

In [5]:
add

,Property ID,Geographic ID,Type,Address,Legal Description,Owner Name,Doing Business As,Appraised Value,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,533670,13720-002-0191,Real,"5711 MOBUD ST SAN ANTONIO, TX 78238",NCB 13720 BLK 2 LOT 19 & SE IRR 20.38 FT OF 18,SALVATION CENTER SAN ANTONIO INC,* EXEMPT *,"803,650",NaN,NaN,NaN
1,713981,18765-065-0120,Real,"5010 TIMBER CLIMB SAN ANTONIO, TX 78250",NCB 18765 BLK 65 LOT 12 GREAT NORTHWEST UT...,SANCHEZ SUSAN E & JUAN A JR,NaN,"153,640",NaN,NaN,NaN
2,1238618,00000-123-8618,Personal,"1716 S SAN MARCOS 204A SAN ANTONIO, TX 78207",1 COMMUNITY DUMPSTERS INC 1716 SA SAN MARCOS ...,1 COMMUNITY DUMPSTERS INC,1 COMMUNITY DUMPSTERS INC,"2,400",NaN,NaN,NaN
3,1160494,13884-001-0290,Real,"10226 SAN PEDRO AVE SAN ANTONIO, TX 78216",NCB 13884 BLK 1 LOT 29 EXC N IRR PART 1.16...,10226 LLC,COLONIAL BUSINESS SOLUTIONS,"1,189,890",NaN,NaN,NaN
4,491024,11754-038-0280,Real,"11103 WEST AVE SAN ANTONIO, TX 78213",NCB: 11754 BLK: 38 LOT: 28 LOCKHILL ESTATES...,11103 WEST AVENUE SAN,89% VACANT - EYE CARE PLAZA,"3,803,460",NaN,NaN,NaN
5,1256323,02082-000-0172,Real,"MENCHACA SAN ANTONIO SAN ANTONIO, TX 78207","NCB 2082 BLK LOT S IRR 146 FT OF 6 & 7, W IRR...",119 PLACID LTD,BOLNER'S FIESTA BRAND SPICES,"2,000,000",NaN,NaN,NaN
6,428697,08983-000-0114,Real,"1205 S SAN IGNACIO AVE SAN ANTONIO, TX 78237",NCB 8983 BLK LOT S 37.5 FT OF W 100 ...,1205 SAN IGNACIO LAND TRUST,NaN,"59,130",NaN,NaN,NaN
7,1230378,17427-007-0013,Real,"12828 SAN PEDRO AVE SAN ANTONIO, TX 78216",NCB 17427 BLK 7 LOT SE IRR 24.83 FT OF 1 (...,12828 SAN PEDRO SAN ANTONIO LLC,HILTON GARDEN INN 118 ROOMS,"8,153,610",NaN,NaN,NaN
8,498603,12059-000-0490,Real,"13131 SAN PEDRO AVE SAN ANTONIO, TX 78216",NCB 12059 BLK LOT 49 EMBASSY PARK UT-1,13131 SAN PEDRO LLC,HOOTERS,"1,290,950",NaN,NaN,NaN
9,425069,08880-024-0220,Real,"136 N SAN FELIPE AVE SAN ANTONIO, TX 78237",NCB 8880 BLK 24 LOT 22 & 23,136 SAN FELIPE LAND TRUST,NaN,"47,000",NaN,NaN,NaN
10,1115730,00014-000-0110,Real,"1400 FLORES ST S SAN ANTONIO, TX 78204",NCB A-14 PT OF TR E ARB E8,1400 FLORES 2014 LTD,SAN ANTONIO PLANNING DEPT,"2,370,760",NaN,NaN,NaN
11,640181,17115-001-0020,Real,"14500 SAN PEDRO AVE SAN ANTONIO, TX 78232",NCB 17115 BLK 1 LOT 2,14500 SAN PEDRO NORTH,SAN PEDRO NORTH MEDICAL DENTAL,"1,275,000",NaN,NaN,NaN
12,103406,00360-048-0010,Real,"600 SAN PEDRO AVE SAN ANTONIO, TX 78212",NCB 360 BLK 48 LOT 1&2,15201 SAN PEDRO LLC,NaN,"367,509",NaN,NaN,NaN
13,441664,09559-189-0060,Real,"1526 SAN ANGELO SAN ANTONIO, TX 78201",NCB 9559 BLK 189 LOT 6 & E 15 FT OF 5 & W 1...,1526 SAN ANGELO LAND TRUST,NaN,"79,130",NaN,NaN,NaN
14,423976,08839-025-0070,Real,"1614 SANTA ANNA SAN ANTONIO, TX 78201",NCB 8839 BLK 25 LOT 7,1614 SANTA ANNA LAND TRUST,NaN,"98,000",NaN,NaN,NaN
15,426174,08932-196-0160,Real,"1623 SAN ANGELO SAN ANTONIO, TX 78201",NCB 8932 BLK 196 LOT 16 EXC N 2.5 FT AT 1623 ...,1623 SAN ANGELO LAND TRUST,NaN,"63,890",NaN,NaN,NaN
16,586016,15674-100-0440,Real,"16240 SAN PEDRO AVE SAN ANTONIO, TX 78232",NCB 15674 BLK LOT 44 LABEL # TXS0575516,16240 SAN PEDRO AVE #44 LAND TR,NaN,"27,780",NaN,NaN,NaN
17,121992,01880-004-0040,Real,"1718 SAN PEDRO AVE SAN ANTONIO, TX 78212",NCB 1880 BLK 4 LOT N 100 FT OF 4,1718 HOLDINGS LLC,LAW OFFICE,"284,690",NaN,NaN,NaN
18,423859,08833-035-0060,Real,"1718 SANTA MONICA SAN ANTONIO, TX 78201",NCB 8833 BLK 35 LOT 6,1718 SANTA MONICA LAND TRUST,NaN,"85,000",NaN,NaN,NaN
19,121751,01864-040-0180,Real,"1807 SAN PEDRO AVE SAN ANTONIO, TX 78212","NCB 1864 BLK 40 LOT N 75 FT OF 18, 19 AND 20",1807 SAN PEDRO LLC,% PHYS - LAW OFFICES,"269,100",NaN,NaN,NaN
20,416509,08485-028-0130,Real,"1923 SANTA MONICA SAN ANTONIO, TX 78201",NCB 8485 BLK 28 LOT 13,1923 SANTA MONICA LAND TRUST,NaN,"71,630",NaN,NaN,NaN
21,428372,08977-010-0050,Real,"710 S SAN DARIO AVE SAN ANTONIO, TX 78237","NCB 8977 BLK 10 LOT W 86.65 FT OF 5, 6 & 7",210 ENTRANCE LTD,NaN,"77,000",NaN,NaN,NaN
22,690603,18159-008-0120,Real,"2106 SAN LUCAS ST SAN ANTONIO, TX 78245",NCB 18159 BLK 8 LOT 12 LACKLAND CITY UT-1...,2106 SAN LUCAS LAND TRUST,NaN,"120,980",NaN,NaN,NaN
23,411118,08251-001-0330,Real,"211 NW 34TH ST SAN ANTONIO, TX 78237",NCB 8251 BLK 1 LOT 33,211 NW 34TH ST SAN ANTONIO BEXAR COUNTY TEXAS ...,NaN,"63,080",NaN,NaN,NaN
24,121014,01816-020-0200,Real,"2201 SAN PEDRO AVE SAN ANTONIO, TX 78212",NCB 1816 BLK 20 LOT 20 & E 30 FT OF 19,2201 SAN PEDRO LLC,SUPERIOR AUTOMOTIVE CENTER,"253,980",NaN,NaN,NaN
25,549836,14401-001-0040,Real,"2714 LESLIE NICOLE SAN ANTONIO, TX 78237",NCB: 14401 BLK: 1 LOT: 4 LOS JARDINES SUBD,2714 LESLIE NICOLE SAN ANTONIO TEXAS LAND TRUST,NaN,"73,210",NaN,NaN,NaN
26,992361,13827-000-0127,Real,"15430 SAN PEDRO AVE SAN ANTONIO, TX 78232",NCB 13827 P-12E ABS 513,281 BROOKHOLLOW DEVELOPERS,NaN,"496,000",NaN,NaN,NaN
27,491752,11790-000-0221,Real,"12241 SAN PEDRO AVE SAN ANTONIO, TX 78216",NCB 11790 BLK LOT S IRR 166.69' OF N IRR 492.0...,281 SAN PEDRO LTD,SONTERRA AUTO/FIGHTER UP CROSSFIT,"1,445,000",NaN,NaN,NaN
28,1044487,92007-151-2100,Personal,"11119 SAN PEDRO AVE SAN ANTONIO, TX 78216",281 STOP INC 11119 SAN PEDRO AVE FURN FIXT INV...,281 STOP INC,281 STOP INC,"78,010",NaN,NaN,NaN
29,145248,03401-000-0160,Real,"3004 SAN LUIS ST SAN ANTONIO, TX 78207",NCB 3401 BLK LOT 16 & 17,3004 SAN LUIS LAND TRUST,NaN,"44,000",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
33475,1254382,00000-125-4382,Personal,"932 CORONADO BLVD UNIVERSAL CITY, TX 78148",WE ROCK THE SPECTRUM SAN ANTONIO 932 CORONADO ...,ZIPPIN SLIDE LLC,WE ROCK THE SPECTRUM SAN ANTONIO,"11,960",NaN,NaN,NaN
33476,985155,92507-200-0000,Personal,"8800 BROADWAY ST 108 SAN ANTONIO, TX 78217-6346",ZITO'S SANDWICH SHOP 008800 00 BROADWAY ST INV...,ZITO'S SANDWICH SHOP,ZITO'S SANDWICH SHOP,"32,850",NaN,NaN,NaN
33477,985153,92507-100-0000,Personal,"6007 CALLAGHAN RD SAN ANTONIO, TX 78228",ZITO'S SANDWICH SHOP 006007 00 CALLAGHAN RD IN...,ZITOS INC,ZITO'S SANDWICH SHOP,"11,500",NaN,NaN,NaN
33478,1151785,00000-115-1785,Personal,"7317 SAN PEDRO AVE SAN ANTONIO, TX 78216",DR PHONEZ 7317 SAN PEDRO AVE INV FURN FIXT EQP...,ZIVASH VENTURES LLC,DR PHONEZ,"7,080",NaN,NaN,NaN
33479,1257721,00000-125-7721,Personal,"13610 SAN PEDRO AVE SAN ANTONIO, TX 78232",ZOES KITCHEN BITTERS 13610 US HIGHWAY 281 N FU...,ZOES TEXAS LLC,ZOES KITCHEN BITTERS,"318,360",NaN,NaN,NaN
33480,490271,11715-005-0420,Real,"9401 SAN PEDRO AVE SAN ANTONIO, TX 78216",NCB 11715 BLK 5 LOT 42,ZOKO LLC,"TOKYO STEAK HOUSE, ART INC","1,072,000",NaN,NaN,NaN
33481,630459,16849-040-0610,Real,"12723 SANDTRAP ST SAN ANTONIO, TX 78217",NCB 16849 BLK 40 LOT 61,ZUEHL DARLENE A,NaN,"133,630",NaN,NaN,NaN
33482,1170187,04361-043-0050,Real,"11726 POPPY SANDS SAN ANTONIO, TX 78245","CB 4361C (AMERICAN LOTUS SUBD UT-2), BLOCK 43 ...",ZUEHL FRANK D JR,NaN,"164,550",NaN,NaN,NaN
33483,1093133,00000-109-3133,Personal,"7400 SAN PEDRO AVE 818 SAN ANTONIO, TX 78216-6226",ZUMIEZ INC 7400 SAN PEDRO AVE STE 818 FURN FIX...,ZUMIEZ INC #304,ZUMIEZ INC,"258,760",NaN,NaN,NaN
33484,420205,08660-008-0210,Real,"503 S SAN GABRIEL AVE SAN ANTONIO, TX 78237","NCB 8660 BLK 8 LOT 21, 22 AND 23",ZUNIGA AMADO T & OLIVIA &,NaN,"62,410",NaN,NaN,NaN
33485,412769,08308-020-0010,Real,"575 N SAN IGNACIO AVE SAN ANTONIO, TX 78228",NCB 8308 BLK 20 LOT 1&2,ZUNIGA ANNIE,NaN,"64,370",NaN,NaN,NaN
33486,440781,09508-003-0130,Real,"232 SANDRA DR SAN ANTONIO, TX 78223",NCB 9508 BLK 3 LOT 13,ZUNIGA ANSELMO G,NaN,"75,760",NaN,NaN,NaN
33487,424396,08860-004-0490,Real,"422 N SAN IGNACIO AVE SAN ANTONIO, TX 78228",NCB 8860 BLK 4 LOT 49- 50,ZUNIGA DANIEL R & FRANCES,NaN,"34,000",NaN,NaN,NaN
33488,155158,03973-002-0250,Real,"3606 SAN LUIS ST SAN ANTONIO, TX 78207",NCB 3973 BLK 2 LOT 25 & N 12.3 FT OF W 20...,ZUNIGA EDDIE R & NATIVIDE A,NaN,"72,520",NaN,NaN,NaN
33489,420313,08661-015-0010,Real,"602 S SAN FELIPE AVE SAN ANTONIO, TX 78237",NCB 8661 BLK 15 LOT 1&2,ZUNIGA EMILIO GOMEZ & MINERVA PRECIADA,NaN,"58,750",NaN,NaN,NaN
33490,1165091,00000-116-5091,Personal,"8425 BANDERA RD 154 SAN ANTONIO, TX 78250",INSTANT IMPRINTS OF SAN ANTONIO 8425 BANDERA R...,"ZUNIGA INTERNATIONAL BUSINESS CONSULTING, INC",INSTANT IMPRINTS OF SAN ANTONIO,"6,090",NaN,NaN,NaN
33491,425054,08879-023-0740,Real,"168 N SAN GABRIEL AVE SAN ANTONIO, TX 78237",NCB 8879 BLK 23 LOT 74- 75,ZUNIGA JESSE &,NaN,"89,600",NaN,NaN,NaN
33492,161136,04011-001-2710,Real,"19584 LEAL ST SAN ANTONIO, TX 78221",CB 4011-1 P-271 ABS 7,ZUNIGA JOSE & SANDRA,MEDINA MOBILE HOME ESTATES,"43,120",NaN,NaN,NaN
33493,429417,08990-011-0140,Real,"862 SW 38TH ST SAN ANTONIO, TX 78237",NCB 8990 BLK 11 LOT W 267.4 FT OF 14,ZUNIGA JOSE ANTONIO & RAMIREZ-FLORES SANDRA PA...,NaN,"69,600",NaN,NaN,NaN
33494,1178309,04400-979-0500,Real,"12703 SAND HOLLY SAN ANTONIO, TX 78253","CB 4400L (ALAMO RANCH UT-44D PH-3A), BLOCK 79 ...",ZUNIGA JOSE MARIA & ANGELA,NaN,"200,030",NaN,NaN,NaN
33495,412364,08297-009-0530,Real,"646 N SAN EDUARDO AVE SAN ANTONIO, TX 78228",NCB 8297 BLK 9 LOT 53 AND 54,ZUNIGA LEOCADIO,NaN,"34,010",NaN,NaN,NaN
33496,412363,08297-009-0510,Real,"650 N SAN EDUARDO AVE SAN ANTONIO, TX 78228",NCB 8297 BLK 009 51.52,ZUNIGA MIKE & ANGIE G,NaN,"32,560",NaN,NaN,NaN
33497,201892,04361-102-0350,Real,"11323 BRONZE SAND SAN ANTONIO, TX 78253",CB 4361A BLK 2 LOT 35 CARACOL CREEK SUB'D UT-2,ZUNIGA RUBEN C & HILDA Y,NaN,"171,510",NaN,NaN,NaN
33498,478337,11225-009-0250,Real,"159 IKE ST SAN ANTONIO, TX 78211",NCB 11225 BLK 9 LOT 25,ZUNIGA SAMUEL T & SANTOS B,NaN,"13,220",NaN,NaN,NaN
33499,147865,03556-004-0040,Real,"114 PANAMA AVE SAN ANTONIO, TX 78210",NCB 3556 BLK 4 LOT 4,ZUNIGA SANDRA,NaN,"171,340",NaN,NaN,NaN
33500,424469,08862-006-0330,Real,"411 N SAN JOAQUIN AVE SAN ANTONIO, TX 78228",NCB 8862 BLK 6 LOT 33- 34-35,ZUNIGA SANDRA A,NaN,"60,470",NaN,NaN,NaN
33501,406138,08021-103-0130,Real,"423 WAGNER AVE SAN ANTONIO, TX 78211",NCB 8021 BLK 103 LOT 13 AND 14,ZUNIGA SANDRA Y,NaN,"74,530",NaN,NaN,NaN
33502,1116747,04413-315-0660,Real,"11923 PERLA JOY SAN ANTONIO, TX 78253","CB 4413C (WESTWINDS NORTH UT-2), BLOCK 15 LOT 66",ZUNIGA SERGIO J & SANDRA N,NaN,"280,550",NaN,NaN,NaN
33503,701155,18400-100-1730,Real,"16203 SANTA CATHRENA SAN ANTONIO, TX 78232",NCB 18400 BLK LOT 173 (MISSION RIDGE UT-...,ZUROVEC CHARLES C & SUE A,NaN,"360,120",NaN,NaN,NaN
33504,701222,18400-100-2420,Real,"607 SAN DIZIER SAN ANTONIO, TX 78232",NCB 18400 BLK LOT 242 (MISSION RIDGE UT...,ZYMAN VIRGINIA L,NaN,"311,340",NaN,NaN,NaN

In [18]:
import difflib
new_add = address['Address'].map(lambda x: difflib.get_close_matches(x, add['Address'], n=1))

TypeError: object of type 'float' has no len()

In [16]:
add

,Property ID,Geographic ID,Type,Address,Legal Description,Owner Name,Doing Business As,Appraised Value,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,533670,13720-002-0191,Real,"5711 MOBUD ST SAN ANTONIO, TX 78238",NCB 13720 BLK 2 LOT 19 & SE IRR 20.38 FT OF 18,SALVATION CENTER SAN ANTONIO INC,* EXEMPT *,"803,650",NaN,NaN,NaN
1,713981,18765-065-0120,Real,"5010 TIMBER CLIMB SAN ANTONIO, TX 78250",NCB 18765 BLK 65 LOT 12 GREAT NORTHWEST UT...,SANCHEZ SUSAN E & JUAN A JR,NaN,"153,640",NaN,NaN,NaN
2,1238618,00000-123-8618,Personal,"1716 S SAN MARCOS 204A SAN ANTONIO, TX 78207",1 COMMUNITY DUMPSTERS INC 1716 SA SAN MARCOS ...,1 COMMUNITY DUMPSTERS INC,1 COMMUNITY DUMPSTERS INC,"2,400",NaN,NaN,NaN
3,1160494,13884-001-0290,Real,"10226 SAN PEDRO AVE SAN ANTONIO, TX 78216",NCB 13884 BLK 1 LOT 29 EXC N IRR PART 1.16...,10226 LLC,COLONIAL BUSINESS SOLUTIONS,"1,189,890",NaN,NaN,NaN
4,491024,11754-038-0280,Real,"11103 WEST AVE SAN ANTONIO, TX 78213",NCB: 11754 BLK: 38 LOT: 28 LOCKHILL ESTATES...,11103 WEST AVENUE SAN,89% VACANT - EYE CARE PLAZA,"3,803,460",NaN,NaN,NaN
5,1256323,02082-000-0172,Real,"MENCHACA SAN ANTONIO SAN ANTONIO, TX 78207","NCB 2082 BLK LOT S IRR 146 FT OF 6 & 7, W IRR...",119 PLACID LTD,BOLNER'S FIESTA BRAND SPICES,"2,000,000",NaN,NaN,NaN
6,428697,08983-000-0114,Real,"1205 S SAN IGNACIO AVE SAN ANTONIO, TX 78237",NCB 8983 BLK LOT S 37.5 FT OF W 100 ...,1205 SAN IGNACIO LAND TRUST,NaN,"59,130",NaN,NaN,NaN
7,1230378,17427-007-0013,Real,"12828 SAN PEDRO AVE SAN ANTONIO, TX 78216",NCB 17427 BLK 7 LOT SE IRR 24.83 FT OF 1 (...,12828 SAN PEDRO SAN ANTONIO LLC,HILTON GARDEN INN 118 ROOMS,"8,153,610",NaN,NaN,NaN
8,498603,12059-000-0490,Real,"13131 SAN PEDRO AVE SAN ANTONIO, TX 78216",NCB 12059 BLK LOT 49 EMBASSY PARK UT-1,13131 SAN PEDRO LLC,HOOTERS,"1,290,950",NaN,NaN,NaN
9,425069,08880-024-0220,Real,"136 N SAN FELIPE AVE SAN ANTONIO, TX 78237",NCB 8880 BLK 24 LOT 22 & 23,136 SAN FELIPE LAND TRUST,NaN,"47,000",NaN,NaN,NaN
10,1115730,00014-000-0110,Real,"1400 FLORES ST S SAN ANTONIO, TX 78204",NCB A-14 PT OF TR E ARB E8,1400 FLORES 2014 LTD,SAN ANTONIO PLANNING DEPT,"2,370,760",NaN,NaN,NaN
11,640181,17115-001-0020,Real,"14500 SAN PEDRO AVE SAN ANTONIO, TX 78232",NCB 17115 BLK 1 LOT 2,14500 SAN PEDRO NORTH,SAN PEDRO NORTH MEDICAL DENTAL,"1,275,000",NaN,NaN,NaN
12,103406,00360-048-0010,Real,"600 SAN PEDRO AVE SAN ANTONIO, TX 78212",NCB 360 BLK 48 LOT 1&2,15201 SAN PEDRO LLC,NaN,"367,509",NaN,NaN,NaN
13,441664,09559-189-0060,Real,"1526 SAN ANGELO SAN ANTONIO, TX 78201",NCB 9559 BLK 189 LOT 6 & E 15 FT OF 5 & W 1...,1526 SAN ANGELO LAND TRUST,NaN,"79,130",NaN,NaN,NaN
14,423976,08839-025-0070,Real,"1614 SANTA ANNA SAN ANTONIO, TX 78201",NCB 8839 BLK 25 LOT 7,1614 SANTA ANNA LAND TRUST,NaN,"98,000",NaN,NaN,NaN
15,426174,08932-196-0160,Real,"1623 SAN ANGELO SAN ANTONIO, TX 78201",NCB 8932 BLK 196 LOT 16 EXC N 2.5 FT AT 1623 ...,1623 SAN ANGELO LAND TRUST,NaN,"63,890",NaN,NaN,NaN
16,586016,15674-100-0440,Real,"16240 SAN PEDRO AVE SAN ANTONIO, TX 78232",NCB 15674 BLK LOT 44 LABEL # TXS0575516,16240 SAN PEDRO AVE #44 LAND TR,NaN,"27,780",NaN,NaN,NaN
17,121992,01880-004-0040,Real,"1718 SAN PEDRO AVE SAN ANTONIO, TX 78212",NCB 1880 BLK 4 LOT N 100 FT OF 4,1718 HOLDINGS LLC,LAW OFFICE,"284,690",NaN,NaN,NaN
18,423859,08833-035-0060,Real,"1718 SANTA MONICA SAN ANTONIO, TX 78201",NCB 8833 BLK 35 LOT 6,1718 SANTA MONICA LAND TRUST,NaN,"85,000",NaN,NaN,NaN
19,121751,01864-040-0180,Real,"1807 SAN PEDRO AVE SAN ANTONIO, TX 78212","NCB 1864 BLK 40 LOT N 75 FT OF 18, 19 AND 20",1807 SAN PEDRO LLC,% PHYS - LAW OFFICES,"269,100",NaN,NaN,NaN
20,416509,08485-028-0130,Real,"1923 SANTA MONICA SAN ANTONIO, TX 78201",NCB 8485 BLK 28 LOT 13,1923 SANTA MONICA LAND TRUST,NaN,"71,630",NaN,NaN,NaN
21,428372,08977-010-0050,Real,"710 S SAN DARIO AVE SAN ANTONIO, TX 78237","NCB 8977 BLK 10 LOT W 86.65 FT OF 5, 6 & 7",210 ENTRANCE LTD,NaN,"77,000",NaN,NaN,NaN
22,690603,18159-008-0120,Real,"2106 SAN LUCAS ST SAN ANTONIO, TX 78245",NCB 18159 BLK 8 LOT 12 LACKLAND CITY UT-1...,2106 SAN LUCAS LAND TRUST,NaN,"120,980",NaN,NaN,NaN
23,411118,08251-001-0330,Real,"211 NW 34TH ST SAN ANTONIO, TX 78237",NCB 8251 BLK 1 LOT 33,211 NW 34TH ST SAN ANTONIO BEXAR COUNTY TEXAS ...,NaN,"63,080",NaN,NaN,NaN
24,121014,01816-020-0200,Real,"2201 SAN PEDRO AVE SAN ANTONIO, TX 78212",NCB 1816 BLK 20 LOT 20 & E 30 FT OF 19,2201 SAN PEDRO LLC,SUPERIOR AUTOMOTIVE CENTER,"253,980",NaN,NaN,NaN
25,549836,14401-001-0040,Real,"2714 LESLIE NICOLE SAN ANTONIO, TX 78237",NCB: 14401 BLK: 1 LOT: 4 LOS JARDINES SUBD,2714 LESLIE NICOLE SAN ANTONIO TEXAS LAND TRUST,NaN,"73,210",NaN,NaN,NaN
26,992361,13827-000-0127,Real,"15430 SAN PEDRO AVE SAN ANTONIO, TX 78232",NCB 13827 P-12E ABS 513,281 BROOKHOLLOW DEVELOPERS,NaN,"496,000",NaN,NaN,NaN
27,491752,11790-000-0221,Real,"12241 SAN PEDRO AVE SAN ANTONIO, TX 78216",NCB 11790 BLK LOT S IRR 166.69' OF N IRR 492.0...,281 SAN PEDRO LTD,SONTERRA AUTO/FIGHTER UP CROSSFIT,"1,445,000",NaN,NaN,NaN
28,1044487,92007-151-2100,Personal,"11119 SAN PEDRO AVE SAN ANTONIO, TX 78216",281 STOP INC 11119 SAN PEDRO AVE FURN FIXT INV...,281 STOP INC,281 STOP INC,"78,010",NaN,NaN,NaN
29,145248,03401-000-0160,Real,"3004 SAN LUIS ST SAN ANTONIO, TX 78207",NCB 3401 BLK LOT 16 & 17,3004 SAN LUIS LAND TRUST,NaN,"44,000",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
33475,1254382,00000-125-4382,Personal,"932 CORONADO BLVD UNIVERSAL CITY, TX 78148",WE ROCK THE SPECTRUM SAN ANTONIO 932 CORONADO ...,ZIPPIN SLIDE LLC,WE ROCK THE SPECTRUM SAN ANTONIO,"11,960",NaN,NaN,NaN
33476,985155,92507-200-0000,Personal,"8800 BROADWAY ST 108 SAN ANTONIO, TX 78217-6346",ZITO'S SANDWICH SHOP 008800 00 BROADWAY ST INV...,ZITO'S SANDWICH SHOP,ZITO'S SANDWICH SHOP,"32,850",NaN,NaN,NaN
33477,985153,92507-100-0000,Personal,"6007 CALLAGHAN RD SAN ANTONIO, TX 78228",ZITO'S SANDWICH SHOP 006007 00 CALLAGHAN RD IN...,ZITOS INC,ZITO'S SANDWICH SHOP,"11,500",NaN,NaN,NaN
33478,1151785,00000-115-1785,Personal,"7317 SAN PEDRO AVE SAN ANTONIO, TX 78216",DR PHONEZ 7317 SAN PEDRO AVE INV FURN FIXT EQP...,ZIVASH VENTURES LLC,DR PHONEZ,"7,080",NaN,NaN,NaN
33479,1257721,00000-125-7721,Personal,"13610 SAN PEDRO AVE SAN ANTONIO, TX 78232",ZOES KITCHEN BITTERS 13610 US HIGHWAY 281 N FU...,ZOES TEXAS LLC,ZOES KITCHEN BITTERS,"318,360",NaN,NaN,NaN
33480,490271,11715-005-0420,Real,"9401 SAN PEDRO AVE SAN ANTONIO, TX 78216",NCB 11715 BLK 5 LOT 42,ZOKO LLC,"TOKYO STEAK HOUSE, ART INC","1,072,000",NaN,NaN,NaN
33481,630459,16849-040-0610,Real,"12723 SANDTRAP ST SAN ANTONIO, TX 78217",NCB 16849 BLK 40 LOT 61,ZUEHL DARLENE A,NaN,"133,630",NaN,NaN,NaN
33482,1170187,04361-043-0050,Real,"11726 POPPY SANDS SAN ANTONIO, TX 78245","CB 4361C (AMERICAN LOTUS SUBD UT-2), BLOCK 43 ...",ZUEHL FRANK D JR,NaN,"164,550",NaN,NaN,NaN
33483,1093133,00000-109-3133,Personal,"7400 SAN PEDRO AVE 818 SAN ANTONIO, TX 78216-6226",ZUMIEZ INC 7400 SAN PEDRO AVE STE 818 FURN FIX...,ZUMIEZ INC #304,ZUMIEZ INC,"258,760",NaN,NaN,NaN
33484,420205,08660-008-0210,Real,"503 S SAN GABRIEL AVE SAN ANTONIO, TX 78237","NCB 8660 BLK 8 LOT 21, 22 AND 23",ZUNIGA AMADO T & OLIVIA &,NaN,"62,410",NaN,NaN,NaN
33485,412769,08308-020-0010,Real,"575 N SAN IGNACIO AVE SAN ANTONIO, TX 78228",NCB 8308 BLK 20 LOT 1&2,ZUNIGA ANNIE,NaN,"64,370",NaN,NaN,NaN
33486,440781,09508-003-0130,Real,"232 SANDRA DR SAN ANTONIO, TX 78223",NCB 9508 BLK 3 LOT 13,ZUNIGA ANSELMO G,NaN,"75,760",NaN,NaN,NaN
33487,424396,08860-004-0490,Real,"422 N SAN IGNACIO AVE SAN ANTONIO, TX 78228",NCB 8860 BLK 4 LOT 49- 50,ZUNIGA DANIEL R & FRANCES,NaN,"34,000",NaN,NaN,NaN
33488,155158,03973-002-0250,Real,"3606 SAN LUIS ST SAN ANTONIO, TX 78207",NCB 3973 BLK 2 LOT 25 & N 12.3 FT OF W 20...,ZUNIGA EDDIE R & NATIVIDE A,NaN,"72,520",NaN,NaN,NaN
33489,420313,08661-015-0010,Real,"602 S SAN FELIPE AVE SAN ANTONIO, TX 78237",NCB 8661 BLK 15 LOT 1&2,ZUNIGA EMILIO GOMEZ & MINERVA PRECIADA,NaN,"58,750",NaN,NaN,NaN
33490,1165091,00000-116-5091,Personal,"8425 BANDERA RD 154 SAN ANTONIO, TX 78250",INSTANT IMPRINTS OF SAN ANTONIO 8425 BANDERA R...,"ZUNIGA INTERNATIONAL BUSINESS CONSULTING, INC",INSTANT IMPRINTS OF SAN ANTONIO,"6,090",NaN,NaN,NaN
33491,425054,08879-023-0740,Real,"168 N SAN GABRIEL AVE SAN ANTONIO, TX 78237",NCB 8879 BLK 23 LOT 74- 75,ZUNIGA JESSE &,NaN,"89,600",NaN,NaN,NaN
33492,161136,04011-001-2710,Real,"19584 LEAL ST SAN ANTONIO, TX 78221",CB 4011-1 P-271 ABS 7,ZUNIGA JOSE & SANDRA,MEDINA MOBILE HOME ESTATES,"43,120",NaN,NaN,NaN
33493,429417,08990-011-0140,Real,"862 SW 38TH ST SAN ANTONIO, TX 78237",NCB 8990 BLK 11 LOT W 267.4 FT OF 14,ZUNIGA JOSE ANTONIO & RAMIREZ-FLORES SANDRA PA...,NaN,"69,600",NaN,NaN,NaN
33494,1178309,04400-979-0500,Real,"12703 SAND HOLLY SAN ANTONIO, TX 78253","CB 4400L (ALAMO RANCH UT-44D PH-3A), BLOCK 79 ...",ZUNIGA JOSE MARIA & ANGELA,NaN,"200,030",NaN,NaN,NaN
33495,412364,08297-009-0530,Real,"646 N SAN EDUARDO AVE SAN ANTONIO, TX 78228",NCB 8297 BLK 9 LOT 53 AND 54,ZUNIGA LEOCADIO,NaN,"34,010",NaN,NaN,NaN
33496,412363,08297-009-0510,Real,"650 N SAN EDUARDO AVE SAN ANTONIO, TX 78228",NCB 8297 BLK 009 51.52,ZUNIGA MIKE & ANGIE G,NaN,"32,560",NaN,NaN,NaN
33497,201892,04361-102-0350,Real,"11323 BRONZE SAND SAN ANTONIO, TX 78253",CB 4361A BLK 2 LOT 35 CARACOL CREEK SUB'D UT-2,ZUNIGA RUBEN C & HILDA Y,NaN,"171,510",NaN,NaN,NaN
33498,478337,11225-009-0250,Real,"159 IKE ST SAN ANTONIO, TX 78211",NCB 11225 BLK 9 LOT 25,ZUNIGA SAMUEL T & SANTOS B,NaN,"13,220",NaN,NaN,NaN
33499,147865,03556-004-0040,Real,"114 PANAMA AVE SAN ANTONIO, TX 78210",NCB 3556 BLK 4 LOT 4,ZUNIGA SANDRA,NaN,"171,340",NaN,NaN,NaN
33500,424469,08862-006-0330,Real,"411 N SAN JOAQUIN AVE SAN ANTONIO, TX 78228",NCB 8862 BLK 6 LOT 33- 34-35,ZUNIGA SANDRA A,NaN,"60,470",NaN,NaN,NaN
33501,406138,08021-103-0130,Real,"423 WAGNER AVE SAN ANTONIO, TX 78211",NCB 8021 BLK 103 LOT 13 AND 14,ZUNIGA SANDRA Y,NaN,"74,530",NaN,NaN,NaN
33502,1116747,04413-315-0660,Real,"11923 PERLA JOY SAN ANTONIO, TX 78253","CB 4413C (WESTWINDS NORTH UT-2), BLOCK 15 LOT 66",ZUNIGA SERGIO J & SANDRA N,NaN,"280,550",NaN,NaN,NaN
33503,701155,18400-100-1730,Real,"16203 SANTA CATHRENA SAN ANTONIO, TX 78232",NCB 18400 BLK LOT 173 (MISSION RIDGE UT-...,ZUROVEC CHARLES C & SUE A,NaN,"360,120",NaN,NaN,NaN
33504,701222,18400-100-2420,Real,"607 SAN DIZIER SAN ANTONIO, TX 78232",NCB 18400 BLK LOT 242 (MISSION RIDGE UT...,ZYMAN VIRGINIA L,NaN,"311,340",NaN,NaN,NaN